// College Math Abstract Algebra Interactive Tutor. No deps.

const fs = require('fs');
const path = require('path');

const DATA_DIR = path.join(__dirname, '..', '..', 'data', 'college-math-abstract-algebra');
const MASTERY_THRESHOLD = 0.8;

const SKILLS = {
  'group-fundamentals': ['group-axioms', 'cayley-tables', 'cyclic-groups', 'order-of-elements', 'generators', 'dihedral-groups', 'symmetric-groups'],
  'subgroups': ['subgroup-test', 'cosets', 'lagranges-theorem', 'normal-subgroups', 'quotient-groups', 'center-of-group'],
  'homomorphisms': ['homomorphism-definition', 'kernels-images', 'first-isomorphism-theorem', 'second-isomorphism-theorem', 'third-isomorphism-theorem'],
  'permutation-groups': ['cycle-notation', 'transpositions', 'parity-even-odd', 'alternating-group', 'conjugacy-classes'],
  'group-actions': ['group-action-definition', 'orbits-stabilizers', 'burnsides-lemma', 'class-equation', 'sylow-theorems'],
  'ring-theory': ['ring-axioms', 'integral-domains', 'polynomial-rings', 'ideals', 'quotient-rings', 'pids-ufds'],
  'field-theory': ['field-extensions', 'algebraic-vs-transcendental', 'minimal-polynomials', 'splitting-fields', 'finite-fields'],
  'galois-theory': ['galois-group', 'fixed-fields', 'fundamental-theorem-galois', 'solvability-by-radicals'],
};

const PROBLEM_BANKS = {
  'group-axioms': {
    problems: [
      { prompt: 'State the four group axioms for a set G with binary operation *.', answer: 'Closure, associativity, identity element, inverse element', solution: '1. Closure: a*b in G. 2. Associativity: (a*b)*c = a*(b*c). 3. Identity: exists e with e*a = a*e = a. 4. Inverse: for each a, exists a^{-1} with a*a^{-1} = e.' },
      { prompt: 'Is (Z, -) a group? Why or why not?', answer: 'No, subtraction is not associative', solution: '(1-2)-3 = -4, but 1-(2-3) = 2. Not associative, so not a group.' },
      { prompt: 'Prove the identity element in a group is unique.', answer: 'If e and f are identities, then e = e*f = f', solution: 'Suppose e and f are both identities. Then e = e*f (f is identity) = f (e is identity). So e = f.' },
      { prompt: 'Is (Z_6, +_6) a group? Verify.', answer: 'Yes', solution: 'Closed under addition mod 6, associative, identity 0, each element a has inverse 6-a. All axioms hold.' },
      { prompt: 'Prove that inverses in a group are unique.', answer: 'If b and c are inverses of a, then b = b*e = b*(a*c) = (b*a)*c = e*c = c', solution: 'Let b and c both be inverses of a. Then b = be = b(ac) = (ba)c = ec = c.' },
    ],
  },
  'cayley-tables': {
    problems: [
      { prompt: 'How many entries does the Cayley table for Z_4 have?', answer: '16', solution: '|G|^2 = 4^2 = 16 entries in a 4x4 table.' },
      { prompt: 'In a Cayley table for a group, can any element appear twice in the same row?', answer: 'No', solution: 'If a*b = a*c, then by left cancellation b = c. Each element appears exactly once per row (Latin square property).' },
      { prompt: 'Complete: In Z_3 = {0,1,2} under addition mod 3, what is 2+2?', answer: '1', solution: '2+2 = 4 ≡ 1 (mod 3).' },
      { prompt: 'How can you tell from a Cayley table if a group is abelian?', answer: 'The table is symmetric about the main diagonal', solution: 'Abelian means a*b = b*a for all a,b. This means entry (i,j) = entry (j,i), i.e., symmetry.' },
    ],
  },
  'cyclic-groups': {
    problems: [
      { prompt: 'What is a cyclic group? Give an example.', answer: 'A group generated by a single element. Example: (Z_n, +)', solution: 'G = <a> = {a^k : k in Z}. Example: Z_6 = <1> under addition mod 6.' },
      { prompt: 'Prove that every cyclic group is abelian.', answer: 'a^m * a^n = a^{m+n} = a^{n+m} = a^n * a^m', solution: 'Let G = <a>. For a^m, a^n in G: a^m * a^n = a^{m+n} = a^{n+m} = a^n * a^m.' },
      { prompt: 'What are all subgroups of Z_12?', answer: '<1>=Z_12, <2>, <3>, <4>, <6>, <0>={0}', solution: 'Subgroups of Z_n correspond to divisors of n. Divisors of 12: 1,2,3,4,6,12. Subgroups: <d> for each divisor d.' },
      { prompt: 'Is Z_7 cyclic? How many generators does it have?', answer: 'Yes, it has phi(7)=6 generators', solution: 'Z_p for prime p is cyclic. Generators are all nonzero elements. phi(7) = 6.' },
      { prompt: 'True or false: Every group of prime order is cyclic.', answer: 'True', solution: 'By Lagrange, the only subgroups have order 1 or p. Any non-identity element generates the whole group.' },
    ],
  },
  'order-of-elements': {
    problems: [
      { prompt: 'What is the order of 3 in Z_12?', answer: '4', solution: 'Smallest positive k with 3k ≡ 0 (mod 12): 3(4)=12≡0. Order is 4.' },
      { prompt: 'If |a| = n in a group G, what is |a^k|?', answer: 'n/gcd(n,k)', solution: '|a^k| = n/gcd(n,k). The order divides n and depends on how k and n share factors.' },
      { prompt: 'What is the order of 5 in Z_8 (under addition)?', answer: '8', solution: 'gcd(5,8)=1, so |5| = 8/1 = 8. 5 generates all of Z_8.' },
      { prompt: 'In S_3, what is the order of the permutation (1 2 3)?', answer: '3', solution: '(1 2 3)^2 = (1 3 2), (1 2 3)^3 = e. Order is 3.' },
    ],
  },
  'generators': {
    problems: [
      { prompt: 'Find all generators of Z_8.', answer: '{1, 3, 5, 7}', solution: 'Generators of Z_n are elements coprime to n. gcd(k,8)=1 for k=1,3,5,7.' },
      { prompt: 'Can a non-cyclic group have a generating set? Give an example.', answer: 'Yes, S_3 = <(1 2), (1 2 3)>', solution: 'S_3 is not cyclic (no element of order 6), but {(1 2), (1 2 3)} generates it.' },
      { prompt: 'How many generators does Z_20 have?', answer: '8', solution: 'phi(20) = 20(1-1/2)(1-1/5) = 8. Elements coprime to 20.' },
    ],
  },
  'dihedral-groups': {
    problems: [
      { prompt: 'What is |D_n| (the dihedral group of a regular n-gon)?', answer: '2n', solution: 'D_n has n rotations and n reflections, total 2n elements.' },
      { prompt: 'Is D_3 isomorphic to S_3?', answer: 'Yes', solution: 'Both have order 6, both are non-abelian. D_3 ≅ S_3.' },
      { prompt: 'In D_4, how many rotations and how many reflections are there?', answer: '4 rotations and 4 reflections', solution: 'Rotations: 0°, 90°, 180°, 270°. Reflections: 4 axes of symmetry. Total: 8 = 2(4).' },
      { prompt: 'Is D_n abelian for n >= 3?', answer: 'No', solution: 'Rotation followed by reflection ≠ reflection followed by rotation in general. D_n is non-abelian for n >= 3.' },
    ],
  },
  'symmetric-groups': {
    problems: [
      { prompt: 'What is |S_4|?', answer: '24', solution: '|S_n| = n! = 4! = 24.' },
      { prompt: 'Write (1 2 3)(1 2) as a single permutation in S_3.', answer: '(1 3)', solution: 'Apply right-to-left: (1 2) sends 1->2, then (1 2 3) sends 2->3. So 1->3. Check: 2->2->3... Result: (1 3).' },
      { prompt: 'How many elements of order 2 does S_3 have?', answer: '3', solution: 'The transpositions: (1 2), (1 3), (2 3). Each has order 2.' },
    ],
  },
  'subgroup-test': {
    problems: [
      { prompt: 'State the two-step subgroup test.', answer: 'H is a subgroup of G if H is nonempty and for all a,b in H, ab^{-1} is in H', solution: 'One-step test: H ≠ ∅ and ab^{-1} ∈ H for all a,b ∈ H. This implies closure, identity, and inverses.' },
      { prompt: 'Prove that the set of even integers is a subgroup of (Z, +).', answer: '0 is even (nonempty), and if 2a, 2b are even, 2a - 2b = 2(a-b) is even', solution: '2Z is nonempty (0 ∈ 2Z). For 2a, 2b ∈ 2Z: 2a + (-2b) = 2(a-b) ∈ 2Z. By subgroup test, 2Z ≤ Z.' },
      { prompt: 'Is {0, 2, 4} a subgroup of Z_6?', answer: 'Yes', solution: 'Nonempty. Check closure: 2+2=4, 2+4=0, 4+4=2, all in {0,2,4}. Identity 0 present. Inverses: 0->0, 2->4, 4->2. Subgroup.' },
    ],
  },
  'cosets': {
    problems: [
      { prompt: 'Let H = {0, 3} in Z_6. Find all left cosets of H.', answer: '0+H={0,3}, 1+H={1,4}, 2+H={2,5}', solution: 'Three cosets: {0,3}, {1,4}, {2,5}. They partition Z_6.' },
      { prompt: 'If |G| = 12 and |H| = 4, how many distinct left cosets of H are there?', answer: '3', solution: '[G:H] = |G|/|H| = 12/4 = 3 cosets.' },
      { prompt: 'True or false: Two left cosets of H in G are either identical or disjoint.', answer: 'True', solution: 'Cosets partition G. If aH ∩ bH ≠ ∅, then aH = bH.' },
    ],
  },
  'lagranges-theorem': {
    problems: [
      { prompt: "State Lagrange's theorem.", answer: 'If H is a subgroup of finite group G, then |H| divides |G|', solution: 'The cosets of H partition G into [G:H] = |G|/|H| equal-sized parts. So |H| divides |G|.' },
      { prompt: "Using Lagrange's theorem, can a group of order 15 have a subgroup of order 6?", answer: 'No, because 6 does not divide 15', solution: 'By Lagrange, subgroup order must divide group order. 6 ∤ 15, so no.' },
      { prompt: "Prove: every group of prime order p is cyclic, using Lagrange's theorem.", answer: 'Any non-identity element a has |<a>| dividing p, so |<a>| = p, so <a> = G', solution: 'Let |G|=p. Take a ≠ e. |<a>| divides p and |<a>| > 1. Since p is prime, |<a>| = p. So G = <a>.' },
      { prompt: 'If |G| = 30, what are the possible orders of elements?', answer: '1, 2, 3, 5, 6, 10, 15, 30', solution: 'By Lagrange, element order divides |G|. Divisors of 30: 1, 2, 3, 5, 6, 10, 15, 30.' },
    ],
  },
  'normal-subgroups': {
    problems: [
      { prompt: 'Define normal subgroup.', answer: 'H is normal in G if gHg^{-1} = H for all g in G (equivalently, gH = Hg)', solution: 'N ◁ G means gNg^{-1} = N for all g ∈ G, or equivalently left and right cosets coincide.' },
      { prompt: 'Is every subgroup of an abelian group normal?', answer: 'Yes', solution: 'In abelian G, gH = Hg for all g since gh = hg. Every subgroup is normal.' },
      { prompt: 'Is A_n normal in S_n?', answer: 'Yes', solution: 'A_n has index 2 in S_n. Any subgroup of index 2 is normal.' },
    ],
  },
  'quotient-groups': {
    problems: [
      { prompt: 'What is the quotient group Z_6/<3>?', answer: 'Z_3 (isomorphic to)', solution: '<3> = {0,3}. Cosets: {0,3}, {1,4}, {2,5}. Three elements with addition mod 3. Z_6/<3> ≅ Z_3.' },
      { prompt: 'If G = Z and N = 5Z, what is G/N?', answer: 'Z/5Z ≅ Z_5', solution: 'Cosets are 0+5Z, 1+5Z, 2+5Z, 3+5Z, 4+5Z. Five residue classes, isomorphic to Z_5.' },
      { prompt: 'Why must N be normal for G/N to be a group?', answer: 'Coset multiplication (aN)(bN) = abN is well-defined only when N is normal', solution: 'Need (aN)(bN) = (ab)N independent of representatives. This requires aNb = abN, which holds iff N is normal.' },
    ],
  },
  'center-of-group': {
    problems: [
      { prompt: 'Define the center Z(G) of a group G.', answer: 'Z(G) = {z in G : zg = gz for all g in G}', solution: 'The center is the set of elements that commute with everything. Always a normal subgroup.' },
      { prompt: 'What is Z(S_3)?', answer: '{e}', solution: 'S_3 is non-abelian. Check: no non-identity element commutes with all others. Z(S_3) = {e}.' },
    ],
  },
  'homomorphism-definition': {
    problems: [
      { prompt: 'Define group homomorphism.', answer: 'A map phi: G -> H such that phi(ab) = phi(a)phi(b) for all a,b in G', solution: 'phi preserves the group operation: the image of a product equals the product of images.' },
      { prompt: 'If phi: G -> H is a homomorphism, prove phi(e_G) = e_H.', answer: 'phi(e) = phi(e*e) = phi(e)phi(e), so phi(e) = e_H by cancellation', solution: 'phi(e) = phi(ee) = phi(e)phi(e). Left-multiply by phi(e)^{-1}: e_H = phi(e).' },
      { prompt: 'Define phi: Z -> Z_n by phi(k) = k mod n. Verify it is a homomorphism.', answer: 'phi(a+b) = (a+b) mod n = (a mod n) + (b mod n) mod n = phi(a) + phi(b)', solution: 'phi(a+b) = (a+b) mod n. By properties of mod: this equals ((a mod n) + (b mod n)) mod n = phi(a)+phi(b) in Z_n.' },
    ],
  },
  'kernels-images': {
    problems: [
      { prompt: 'Define the kernel of a homomorphism phi: G -> H.', answer: 'ker(phi) = {g in G : phi(g) = e_H}', solution: 'The kernel is the preimage of the identity. It is always a normal subgroup of G.' },
      { prompt: 'If phi: Z -> Z_6 is phi(n) = n mod 6, what is ker(phi)?', answer: '6Z = {..., -6, 0, 6, 12, ...}', solution: 'ker(phi) = {n : n mod 6 = 0} = 6Z, the multiples of 6.' },
      { prompt: 'Prove: phi is injective if and only if ker(phi) = {e}.', answer: 'If ker={e} and phi(a)=phi(b), then phi(ab^{-1})=e so ab^{-1}=e so a=b', solution: '(=>) If phi(g)=e and phi injective, then phi(g)=phi(e) so g=e. (<=) If phi(a)=phi(b), phi(ab^{-1})=e, so ab^{-1}=e, so a=b.' },
    ],
  },
  'first-isomorphism-theorem': {
    problems: [
      { prompt: 'State the First Isomorphism Theorem.', answer: 'If phi: G -> H is a homomorphism, then G/ker(phi) is isomorphic to im(phi)', solution: 'G/ker(phi) ≅ phi(G). The quotient by the kernel is isomorphic to the image.' },
      { prompt: 'Apply the First Isomorphism Theorem to phi: Z -> Z_n, phi(k) = k mod n.', answer: 'Z/nZ ≅ Z_n', solution: 'ker(phi) = nZ, im(phi) = Z_n. By FIT: Z/nZ ≅ Z_n.' },
      { prompt: 'If phi: G -> H is surjective with |ker(phi)| = 5 and |G| = 30, what is |H|?', answer: '6', solution: 'By FIT: G/ker(phi) ≅ H. |H| = |G|/|ker(phi)| = 30/5 = 6.' },
    ],
  },
  'second-isomorphism-theorem': {
    problems: [
      { prompt: 'State the Second Isomorphism Theorem.', answer: 'If H ≤ G and N ◁ G, then HN/N ≅ H/(H ∩ N)', solution: 'Also called the Diamond Isomorphism Theorem. HN is a subgroup, N ◁ HN, H∩N ◁ H, and the quotients are isomorphic.' },
    ],
  },
  'third-isomorphism-theorem': {
    problems: [
      { prompt: 'State the Third Isomorphism Theorem.', answer: 'If N ⊆ M are both normal in G, then (G/N)/(M/N) ≅ G/M', solution: 'Quotient of a quotient: (G/N)/(M/N) ≅ G/M. "Cancel the N."' },
    ],
  },
  'cycle-notation': {
    problems: [
      { prompt: 'Write the permutation (1->3, 2->1, 3->2) in cycle notation.', answer: '(1 3 2)', solution: '1->3->2->1, so the cycle is (1 3 2).' },
      { prompt: 'Compute (1 2 3)(4 5) as a product of disjoint cycles in S_5.', answer: '(1 2 3)(4 5) — already disjoint', solution: 'These cycles are already disjoint since they act on separate elements.' },
      { prompt: 'What is the order of (1 2 3)(4 5 6 7) in S_7?', answer: '12', solution: 'Order = lcm(length of cycles) = lcm(3, 4) = 12.' },
      { prompt: 'Compute (1 2)(1 3) in S_3.', answer: '(1 3 2)', solution: 'Right to left: (1 3) sends 1->3, then (1 2) fixes 3. 1->3. (1 3) sends 3->1, (1 2) sends 1->2. 3->2. (1 3) fixes 2, (1 2) sends 2->1. 2->1. Result: (1 3 2).' },
    ],
  },
  'transpositions': {
    problems: [
      { prompt: 'Write (1 2 3 4) as a product of transpositions.', answer: '(1 4)(1 3)(1 2)', solution: '(1 2 3 4) = (1 4)(1 3)(1 2). An n-cycle needs n-1 transpositions.' },
      { prompt: 'How many transpositions are needed to express an n-cycle?', answer: 'n - 1', solution: '(a_1 a_2 ... a_n) = (a_1 a_n)(a_1 a_{n-1})...(a_1 a_2). Exactly n-1.' },
    ],
  },
  'parity-even-odd': {
    problems: [
      { prompt: 'Is (1 2 3)(4 5) even or odd?', answer: 'Odd', solution: '(1 2 3) = 2 transpositions (even). (4 5) = 1 transposition (odd). Total: 3 transpositions. Odd.' },
      { prompt: 'Is the identity permutation even or odd?', answer: 'Even', solution: 'Identity = product of 0 transpositions. 0 is even.' },
      { prompt: 'Can a permutation be both even and odd?', answer: 'No', solution: 'The parity of a permutation is well-defined. This is a theorem (sign homomorphism).' },
    ],
  },
  'alternating-group': {
    problems: [
      { prompt: 'What is |A_4|?', answer: '12', solution: '|A_n| = n!/2 = 24/2 = 12.' },
      { prompt: 'Is A_3 cyclic?', answer: 'Yes', solution: 'A_3 = {e, (1 2 3), (1 3 2)}. Order 3, prime, hence cyclic.' },
      { prompt: 'For n >= 5, is A_n simple?', answer: 'Yes', solution: 'A_n is simple for n >= 5 (no nontrivial normal subgroups). This is key to proving S_5 is not solvable.' },
    ],
  },
  'conjugacy-classes': {
    problems: [
      { prompt: 'Two elements of S_n are conjugate iff they have the same ___.', answer: 'Cycle type', solution: 'In S_n, conjugacy classes correspond to partitions of n (cycle types).' },
      { prompt: 'How many conjugacy classes does S_4 have?', answer: '5', solution: 'Partitions of 4: (4), (3,1), (2,2), (2,1,1), (1,1,1,1). Five classes.' },
    ],
  },
  'group-action-definition': {
    problems: [
      { prompt: 'Define a group action of G on a set X.', answer: 'A map G x X -> X with e*x = x and (gh)*x = g*(h*x) for all g,h in G, x in X', solution: 'Identity acts trivially and the action is compatible with the group operation.' },
      { prompt: 'Give an example of a group action.', answer: 'S_n acts on {1,...,n} by permutation', solution: 'sigma * i = sigma(i). Identity fixes all, composition of permutations corresponds to sequential action.' },
    ],
  },
  'orbits-stabilizers': {
    problems: [
      { prompt: 'State the Orbit-Stabilizer Theorem.', answer: '|Orb(x)| * |Stab(x)| = |G|', solution: 'For finite group G acting on X: |G| = |Orb(x)| × |Stab(x)| for any x in X.' },
      { prompt: 'If |G| = 24 and |Stab(x)| = 6, what is |Orb(x)|?', answer: '4', solution: '|Orb(x)| = |G|/|Stab(x)| = 24/6 = 4.' },
    ],
  },
  'burnsides-lemma': {
    problems: [
      { prompt: "State Burnside's Lemma.", answer: 'Number of orbits = (1/|G|) * sum of |Fix(g)| over all g in G', solution: "Burnside: |X/G| = (1/|G|) Σ_{g∈G} |X^g| where X^g = {x : g·x = x}." },
      { prompt: 'How many distinct colorings of a square with 2 colors (up to rotation)?', answer: '6', solution: 'G = rotations = {0°,90°,180°,270°}. Fix counts: 16,2,4,2. (1/4)(24) = 6.' },
    ],
  },
  'class-equation': {
    problems: [
      { prompt: 'State the class equation for a finite group G.', answer: '|G| = |Z(G)| + sum of [G:C(x_i)] over conjugacy class representatives x_i not in Z(G)', solution: 'Partition G by conjugacy classes: singletons from center + non-trivial classes of size [G:C_G(x)].' },
    ],
  },
  'sylow-theorems': {
    problems: [
      { prompt: 'State the First Sylow Theorem.', answer: 'If p^k divides |G|, then G has a subgroup of order p^k', solution: 'In particular, if p^a is the highest power of p dividing |G|, a Sylow p-subgroup of order p^a exists.' },
      { prompt: 'If |G| = 12, how many Sylow 3-subgroups could G have?', answer: '1 or 4', solution: 'n_3 divides 12/3 = 4 and n_3 ≡ 1 mod 3. Options: 1 or 4.' },
      { prompt: 'If n_p = 1 for a Sylow p-subgroup, what can you conclude?', answer: 'The Sylow p-subgroup is normal in G', solution: 'A unique Sylow p-subgroup is normal because it is fixed by conjugation.' },
    ],
  },
  'ring-axioms': {
    problems: [
      { prompt: 'What are the axioms for a ring (R, +, *)?', answer: '(R,+) is an abelian group, * is associative, and * distributes over +', solution: 'Abelian group under +, monoid under * (with or without identity), left and right distributive laws.' },
      { prompt: 'Is (Z, +, *) a ring? A commutative ring? A ring with unity?', answer: 'Yes to all three', solution: 'Z has abelian group (Z,+), associative/commutative multiplication, unity 1, and distributive law holds.' },
      { prompt: 'Give an example of a non-commutative ring.', answer: 'M_2(R), the 2x2 matrices over R', solution: 'Matrix multiplication is not commutative in general. AB ≠ BA for most 2x2 matrices.' },
    ],
  },
  'integral-domains': {
    problems: [
      { prompt: 'Define integral domain.', answer: 'A commutative ring with unity and no zero divisors', solution: 'If ab = 0 then a = 0 or b = 0. Cancellation law holds.' },
      { prompt: 'Is Z_6 an integral domain?', answer: 'No', solution: '2 * 3 = 0 in Z_6, but 2 ≠ 0 and 3 ≠ 0. Zero divisors exist.' },
      { prompt: 'Is Z_7 an integral domain?', answer: 'Yes', solution: 'Z_p for prime p is an integral domain (in fact a field).' },
    ],
  },
  'polynomial-rings': {
    problems: [
      { prompt: 'Is R[x] (polynomials over a field R) a PID?', answer: 'Yes', solution: 'F[x] for a field F is a PID — every ideal is generated by a single polynomial.' },
      { prompt: 'What is the degree of (x^2+1)(x^3+x) in Z[x]?', answer: '5', solution: 'deg(fg) = deg(f) + deg(g) = 2 + 3 = 5 (in an integral domain).' },
    ],
  },
  'ideals': {
    problems: [
      { prompt: 'Define ideal of a ring R.', answer: 'A subring I of R such that for all r in R and a in I, ra and ar are in I', solution: 'An ideal absorbs multiplication: rI ⊆ I and Ir ⊆ I. This makes R/I a ring.' },
      { prompt: 'What are the ideals of Z?', answer: 'nZ for each n >= 0', solution: 'Every ideal of Z is principal: I = (n) = nZ. Z is a PID.' },
      { prompt: 'Is (2, x) = {2f(x) + xg(x) : f,g in Z[x]} a principal ideal of Z[x]?', answer: 'No', solution: 'No single polynomial generates (2, x). Z[x] is not a PID even though Z is.' },
    ],
  },
  'quotient-rings': {
    problems: [
      { prompt: 'What is Z[x]/(x^2 + 1) isomorphic to?', answer: 'C (the complex numbers), when working over R[x]', solution: 'In R[x]/(x^2+1), x^2 = -1. Elements: a + bx with a,b real. This is C.' },
      { prompt: 'What is Z/6Z isomorphic to?', answer: 'Z_6', solution: 'Z/6Z = {0+6Z, 1+6Z, ..., 5+6Z} ≅ Z_6 with addition and multiplication mod 6.' },
    ],
  },
  'pids-ufds': {
    problems: [
      { prompt: 'Define PID and UFD.', answer: 'PID: every ideal is principal. UFD: every nonzero non-unit factors uniquely into irreducibles', solution: 'PID = Principal Ideal Domain. UFD = Unique Factorization Domain. Every PID is a UFD, but not conversely.' },
      { prompt: 'Is Z a PID? Is Z[x] a PID?', answer: 'Z is a PID. Z[x] is not a PID (but is a UFD)', solution: 'Z: every ideal is (n). Z[x]: the ideal (2, x) is not principal. But Z[x] is a UFD.' },
    ],
  },
  'field-extensions': {
    problems: [
      { prompt: 'What is [Q(sqrt(2)):Q]?', answer: '2', solution: 'Q(sqrt(2)) = {a + b*sqrt(2) : a,b in Q}. Basis: {1, sqrt(2)}. Degree 2.' },
      { prompt: 'What is the degree [Q(cube_root(2)):Q]?', answer: '3', solution: 'Minimal polynomial of cube_root(2) over Q is x^3-2 (irreducible by Eisenstein). Degree 3.' },
      { prompt: 'State the Tower Law for field extensions.', answer: '[L:K] = [L:F][F:K] when K ⊆ F ⊆ L', solution: 'Degrees multiply in towers: [L:K] = [L:F] · [F:K].' },
    ],
  },
  'algebraic-vs-transcendental': {
    problems: [
      { prompt: 'Is sqrt(2) algebraic or transcendental over Q?', answer: 'Algebraic', solution: 'sqrt(2) is a root of x^2 - 2 ∈ Q[x]. Therefore algebraic.' },
      { prompt: 'Is pi algebraic or transcendental over Q?', answer: 'Transcendental', solution: 'Lindemann (1882) proved pi is not a root of any polynomial with rational coefficients.' },
    ],
  },
  'minimal-polynomials': {
    problems: [
      { prompt: 'What is the minimal polynomial of sqrt(2) over Q?', answer: 'x^2 - 2', solution: 'x^2-2 is monic, irreducible over Q (no rational roots), and has sqrt(2) as a root.' },
      { prompt: 'The minimal polynomial of alpha over F is always ___.', answer: 'Irreducible over F', solution: 'By definition, it is the monic polynomial of least degree in F[x] having alpha as a root. It must be irreducible.' },
    ],
  },
  'splitting-fields': {
    problems: [
      { prompt: 'What is the splitting field of x^2 - 2 over Q?', answer: 'Q(sqrt(2))', solution: 'x^2-2 = (x-sqrt(2))(x+sqrt(2)). Both roots lie in Q(sqrt(2)). Splitting field is Q(sqrt(2)).' },
      { prompt: 'Is the splitting field of a polynomial unique?', answer: 'Yes, up to isomorphism', solution: 'Splitting fields exist and are unique up to isomorphism over the base field.' },
    ],
  },
  'finite-fields': {
    problems: [
      { prompt: 'For which values of q does a finite field of order q exist?', answer: 'q = p^n for a prime p and positive integer n', solution: 'Finite fields exist of order p^n and only those. GF(p^n) or F_{p^n}.' },
      { prompt: 'Is the multiplicative group of a finite field cyclic?', answer: 'Yes', solution: 'F*_q = F_q - {0} is always a cyclic group of order q-1.' },
    ],
  },
  'galois-group': {
    problems: [
      { prompt: 'Define the Galois group Gal(L/K).', answer: 'The group of automorphisms of L that fix every element of K', solution: 'Gal(L/K) = {sigma in Aut(L) : sigma(a) = a for all a in K}.' },
      { prompt: 'What is Gal(Q(sqrt(2))/Q)?', answer: 'Z_2', solution: 'Two automorphisms: identity and sqrt(2) -> -sqrt(2). Gal ≅ Z_2.' },
    ],
  },
  'fixed-fields': {
    problems: [
      { prompt: 'If H ≤ Gal(L/K), what is the fixed field L^H?', answer: 'L^H = {a in L : sigma(a) = a for all sigma in H}', solution: 'The set of elements fixed by every automorphism in H. It is an intermediate field K ⊆ L^H ⊆ L.' },
    ],
  },
  'fundamental-theorem-galois': {
    problems: [
      { prompt: 'State the Fundamental Theorem of Galois Theory (main correspondence).', answer: 'There is a bijection between intermediate fields of L/K and subgroups of Gal(L/K), given by E <-> Gal(L/E)', solution: 'The correspondence reverses inclusion: larger subgroups correspond to smaller intermediate fields. Normal subgroups correspond to normal (Galois) extensions.' },
    ],
  },
  'solvability-by-radicals': {
    problems: [
      { prompt: 'What does "solvable by radicals" mean for a polynomial?', answer: 'Its roots can be expressed using +, -, *, /, and nth roots starting from the coefficients', solution: 'The general quintic is NOT solvable by radicals (Abel-Ruffini). A polynomial is solvable by radicals iff its Galois group is a solvable group.' },
      { prompt: 'Why is the general quintic not solvable by radicals?', answer: 'Its Galois group is S_5 which is not solvable (A_5 is simple and non-abelian)', solution: 'S_5 has composition series with A_5 which is simple and non-abelian, so S_5 is not solvable.' },
    ],
  },
};

// File I/O

function ensureDataDir() { if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true }); }

function profilePath(id) { return path.join(DATA_DIR, String(id).replace(/[^a-zA-Z0-9_-]/g, '_') + '.json'); }

function loadProfile(id) {
  const fp = profilePath(id);
  if (fs.existsSync(fp)) {
    try { return JSON.parse(fs.readFileSync(fp, 'utf8')); }
    catch { fs.renameSync(fp, fp + '.corrupt.' + Date.now()); }
  }
  return { studentId: id, createdAt: new Date().toISOString(), assessments: [], skills: {} };
}

function saveProfile(p) { ensureDataDir(); fs.writeFileSync(profilePath(p.studentId), JSON.stringify(p, null, 2), 'utf8'); }

// Helpers

function calcMastery(attempts) {
  if (!attempts || !attempts.length) return 0;
  const recent = attempts.slice(-5).filter(a => a.total > 0);
  return recent.length ? Math.round(recent.reduce((s, a) => s + a.score / a.total, 0) / recent.length * 100) / 100 : 0;
}

function masteryLabel(r) { return r >= 0.9 ? 'mastered' : r >= MASTERY_THRESHOLD ? 'proficient' : r >= 0.6 ? 'developing' : r > 0 ? 'emerging' : 'not-started'; }

function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [a[i], a[j]] = [a[j], a[i]]; }
  return a;
}

function pick(arr, n) { return shuffle(arr).slice(0, Math.min(n, arr.length)); }

function norm(s) { return String(s).toLowerCase().trim().replace(/\s+/g, ' '); }

// Exercise generation

function generateExercise(skill, count = 5) {
  const bank = PROBLEM_BANKS[skill];
  if (!bank || !bank.problems) return { error: `No problem bank for ${skill}` };
  const items = pick(bank.problems, count);
  return { type: 'abstract-algebra', skill, count: items.length, instruction: 'Solve each problem. Show your reasoning.', items };
}

function checkAnswer(type, expected, answer) {
  return norm(expected) === norm(answer);
}

function resolveSkill(skill) {
  for (const [cat, skills] of Object.entries(SKILLS)) {
    if (skills.includes(skill)) return { category: cat, skill };
  }
  return null;
}

// Public API

class AbstractAlgebra {
  getProfile(id) {
    const p = loadProfile(id);
    return { studentId: p.studentId, createdAt: p.createdAt, totalAssessments: p.assessments.length };
  }

  recordAssessment(id, category, skill, score, total, notes = '') {
    if (!SKILLS[category]) throw new Error(`Unknown category: ${category}`);
    if (!SKILLS[category].includes(skill)) throw new Error(`Unknown skill '${skill}' in ${category}`);
    if (typeof total !== 'number' || total <= 0) throw new Error('total must be positive');
    if (typeof score !== 'number' || score < 0 || score > total) throw new Error(`score must be 0-${total}`);

    const p = loadProfile(id);
    const entry = { date: new Date().toISOString(), category, skill, score, total, notes };
    p.assessments.push(entry);
    const key = `${category}/${skill}`;
    if (!p.skills[key]) p.skills[key] = { attempts: [] };
    p.skills[key].attempts.push({ date: entry.date, score, total });
    p.skills[key].mastery = calcMastery(p.skills[key].attempts);
    p.skills[key].label = masteryLabel(p.skills[key].mastery);
    saveProfile(p);
    return { studentId: id, skill: key, score: `${score}/${total}`, mastery: p.skills[key].mastery, label: p.skills[key].label };
  }

  getProgress(id) {
    const p = loadProfile(id);
    const results = {};
    let mastered = 0, total = 0;
    for (const [cat, skills] of Object.entries(SKILLS)) {
      results[cat] = {};
      for (const sk of skills) {
        total++;
        const d = p.skills[`${cat}/${sk}`];
        results[cat][sk] = d ? { mastery: d.mastery, label: d.label } : { mastery: 0, label: 'not-started' };
        if (d && d.mastery >= MASTERY_THRESHOLD) mastered++;
      }
    }
    return { studentId: id, mastered, total, overallPct: total > 0 ? Math.round(mastered / total * 100) : 0, skills: results };
  }

  getNextSkills(id, count = 5) {
    const p = loadProfile(id);
    const candidates = [];
    for (const [cat, skills] of Object.entries(SKILLS)) {
      for (const sk of skills) {
        const d = p.skills[`${cat}/${sk}`];
        const m = d ? d.mastery : 0;
        if (m < MASTERY_THRESHOLD) candidates.push({ category: cat, skill: sk, mastery: m, label: d ? d.label : 'not-started' });
      }
    }
    const order = { developing: 0, emerging: 1, 'not-started': 2 };
    candidates.sort((a, b) => (order[a.label] ?? 3) - (order[b.label] ?? 3) || b.mastery - a.mastery);
    return { studentId: id, next: candidates.slice(0, count) };
  }

  getReport(id) {
    const p = loadProfile(id);
    return { studentId: id, progress: this.getProgress(id), recentAssessments: p.assessments.slice(-20).reverse() };
  }

  listStudents() {
    ensureDataDir();
    const files = fs.readdirSync(DATA_DIR).filter(f => f.endsWith('.json'));
    return { count: files.length, students: files.map(f => f.replace(/\.json$/, '')) };
  }

  getSkillCatalog() {
    let total = 0;
    const catalog = {};
    for (const [cat, skills] of Object.entries(SKILLS)) { total += skills.length; catalog[cat] = [...skills]; }
    return { skills: catalog, totalSkills: total };
  }

  generateExercise(skill, count = 5) { return generateExercise(skill, count); }

  checkAnswer(type, expected, answer) { return { correct: checkAnswer(type, expected, answer), expected, studentAnswer: answer }; }

  generateLesson(id) {
    const target = this.getNextSkills(id, 3).next[0];
    if (!target) return { message: 'All skills are proficient!' };
    const exercise = generateExercise(target.skill, 5);
    return {
      studentId: id, targetSkill: target, exercise,
      lessonPlan: {
        review: 'Review prerequisite concepts (2-3 min)',
        teach: `Introduce/reinforce: ${target.category} -> ${target.skill}`,
        practice: `Complete ${exercise.count || 0} practice problems`,
        apply: 'Work a proof or application problem using concrete examples (Z_n, S_n, D_n)',
      },
    };
  }
}

module.exports = AbstractAlgebra;

// CLI
if (require.main === module) {
  const args = process.argv.slice(2);
  const cmd = args[0];
  const api = new AbstractAlgebra();
  const out = d => console.log(JSON.stringify(d, null, 2));

  try {
    switch (cmd) {
      case 'start': {
        const [, id] = args;
        if (!id) throw new Error('Usage: start <id>');
        out({ action: 'start', profile: api.getProfile(id), nextSkills: api.getNextSkills(id) });
        break;
      }
      case 'lesson': { const [, id] = args; if (!id) throw new Error('Usage: lesson <id>'); out(api.generateLesson(id)); break; }
      case 'exercise': {
        const [, id, skill] = args;
        if (!id) throw new Error('Usage: exercise <id> [skill]');
        if (skill) { out(api.generateExercise(skill, 5)); }
        else { const n = api.getNextSkills(id, 1).next; out(n.length ? api.generateExercise(n[0].skill, 5) : { message: 'All skills proficient!' }); }
        break;
      }
      case 'check': {
        const [, , type, expected, answer] = args;
        if (!type || expected === undefined || answer === undefined) throw new Error('Usage: check <id> <type> <expected> <answer>');
        out(api.checkAnswer(type, expected, answer));
        break;
      }
      case 'record': {
        const [, id, cat, skill, sc, tot, ...notes] = args;
        if (!id || !cat || !skill || !sc || !tot) throw new Error('Usage: record <id> <cat> <skill> <score> <total>');
        out(api.recordAssessment(id, cat, skill, Number(sc), Number(tot), notes.join(' ')));
        break;
      }
      case 'progress': { const [, id] = args; if (!id) throw new Error('Usage: progress <id>'); out(api.getProgress(id)); break; }
      case 'report': { const [, id] = args; if (!id) throw new Error('Usage: report <id>'); out(api.getReport(id)); break; }
      case 'next': { const [, id, n] = args; if (!id) throw new Error('Usage: next <id> [count]'); out(api.getNextSkills(id, n ? Number(n) : 5)); break; }
      case 'catalog': { out(api.getSkillCatalog()); break; }
      case 'students': { out(api.listStudents()); break; }
      default: out({ usage: 'node abstract-algebra.js <command> [args]', commands: ['start','lesson','exercise','check','record','progress','report','next','catalog','students'] });
    }
  } catch (err) { out({ error: err.message }); process.exit(1); }
}
