// eClaw HS Earth & Space Science Tutor (9-12). No deps.

const fs = require('fs');
const path = require('path');

const DATA_DIR = path.join(__dirname, '..', '..', 'data', 'hs-science-earth-space');
const MASTERY_THRESHOLD = 0.8;

const SKILLS = {
  'standard': {
    'geology-plate-tectonics': ['earth-layers', 'plate-boundaries', 'continental-drift', 'seafloor-spreading'],
    'mineralogy': ['rock-cycle', 'mineral-identification', 'weathering-erosion', 'soil-science'],
    'atmospheric-science': ['atmosphere-layers', 'atmospheric-circulation', 'weather-fronts', 'severe-weather'],
    'oceanography': ['ocean-currents', 'tides', 'ocean-chemistry', 'marine-ecosystems'],
    'climate-change': ['greenhouse-effect', 'paleoclimate', 'climate-models', 'mitigation-adaptation'],
    'astronomy': ['stellar-evolution', 'hr-diagram', 'solar-system', 'cosmology'],
    'space-exploration': ['telescopes-instruments', 'space-missions', 'exoplanets', 'habitability'],
    'natural-hazards': ['earthquakes', 'volcanic-eruptions', 'hurricanes-tornadoes', 'hazard-risk-assessment'],
  },
  'ap-environmental': {
    'geology-plate-tectonics': ['earth-layers', 'plate-boundaries', 'continental-drift', 'seafloor-spreading', 'hotspots-mantle-plumes', 'geologic-time-scale'],
    'mineralogy': ['rock-cycle', 'mineral-identification', 'weathering-erosion', 'soil-science', 'resource-extraction', 'sedimentary-environments'],
    'atmospheric-science': ['atmosphere-layers', 'atmospheric-circulation', 'weather-fronts', 'severe-weather', 'air-quality-pollution', 'ozone-depletion'],
    'oceanography': ['ocean-currents', 'tides', 'ocean-chemistry', 'marine-ecosystems', 'ocean-acidification', 'thermohaline-circulation'],
    'climate-change': ['greenhouse-effect', 'paleoclimate', 'climate-models', 'mitigation-adaptation', 'carbon-cycle-feedbacks', 'climate-policy'],
    'astronomy': ['stellar-evolution', 'hr-diagram', 'solar-system', 'cosmology', 'spectroscopy', 'galactic-structure'],
    'space-exploration': ['telescopes-instruments', 'space-missions', 'exoplanets', 'habitability', 'astrobiology', 'space-resource-utilization'],
    'natural-hazards': ['earthquakes', 'volcanic-eruptions', 'hurricanes-tornadoes', 'hazard-risk-assessment', 'tsunami-science', 'wildfire-ecology'],
  },
};

const CONTENT_BANKS = {
  // ===== Geology / Plate Tectonics =====
  'earth-layers': { questions: [
    { q: 'What are the four main layers of the Earth from outermost to innermost?', a: 'crust, mantle, outer core, inner core', alt: ['crust mantle outer core inner core'], type: 'recall' },
    { q: 'The asthenosphere is important for plate tectonics because it is what?', a: 'partially molten and allows tectonic plates to move', alt: ['semi-plastic layer plates float on'], type: 'concept' },
    { q: 'What is the lithosphere?', a: 'the rigid outer layer composed of the crust and uppermost mantle', alt: ['crust and upper mantle'], type: 'recall' },
    { q: 'The inner core is solid despite extreme temperatures because of what?', a: 'immense pressure', alt: ['extreme pressure keeps it solid', 'high pressure'], type: 'concept' },
    { q: 'What evidence do seismic waves provide about Earth\'s interior?', a: 'changes in wave speed and shadow zones reveal layer boundaries and compositions', alt: ['seismic wave refraction shows layers'], type: 'concept' },
    { q: 'P-waves differ from S-waves how?', a: 'P-waves are compressional and travel through all media; S-waves are shear and cannot travel through liquids', alt: ['p waves go through liquids s waves do not'], type: 'recall' },
    { q: 'What is the Moho discontinuity?', a: 'the boundary between the crust and the mantle', alt: ['crust mantle boundary'], type: 'recall' },
    { q: 'Earth\'s magnetic field is generated by what process?', a: 'convection of liquid iron in the outer core (the geodynamo)', alt: ['movement of molten iron in outer core'], type: 'concept' },
  ]},
  'plate-boundaries': { questions: [
    { q: 'What are the three types of plate boundaries?', a: 'convergent, divergent, and transform', alt: ['convergent divergent transform'], type: 'recall' },
    { q: 'What forms at a convergent boundary where oceanic crust meets continental crust?', a: 'a subduction zone with a deep ocean trench and volcanic arc', alt: ['subduction zone'], type: 'concept' },
    { q: 'Mid-ocean ridges form at what type of boundary?', a: 'divergent boundary', alt: ['divergent'], type: 'recall' },
    { q: 'The San Andreas Fault is an example of what type of boundary?', a: 'transform boundary', alt: ['transform'], type: 'application' },
    { q: 'When two continental plates converge, what forms?', a: 'mountain ranges such as the Himalayas', alt: ['mountains', 'mountain range'], type: 'concept' },
    { q: 'What is subduction?', a: 'the process where one tectonic plate slides beneath another', alt: ['one plate goes under another'], type: 'recall' },
    { q: 'Divergent boundaries in continental crust produce what feature?', a: 'rift valleys', alt: ['rift valley', 'continental rift'], type: 'recall' },
    { q: 'Which type of boundary is most associated with shallow earthquakes only?', a: 'transform boundary', alt: ['transform'], type: 'concept' },
  ]},
  'continental-drift': { questions: [
    { q: 'Who proposed the theory of continental drift?', a: 'Alfred Wegener', alt: ['Wegener'], type: 'recall' },
    { q: 'What was the supercontinent called that Wegener proposed?', a: 'Pangaea', alt: ['Pangea'], type: 'recall' },
    { q: 'What fossil evidence supports continental drift?', a: 'identical fossils like Mesosaurus found on separate continents', alt: ['matching fossils on different continents', 'Mesosaurus'], type: 'concept' },
    { q: 'Why was continental drift initially rejected by scientists?', a: 'Wegener could not explain the mechanism that moves continents', alt: ['no mechanism', 'lacked a driving mechanism'], type: 'concept' },
    { q: 'What geological evidence supports continental drift?', a: 'matching rock formations and mountain chains across continents', alt: ['matching rocks across continents'], type: 'concept' },
    { q: 'Glacial striations found in tropical regions suggest what?', a: 'those landmasses were once near the poles', alt: ['continents were in different positions'], type: 'application' },
  ]},
  'seafloor-spreading': { questions: [
    { q: 'Who proposed the theory of seafloor spreading?', a: 'Harry Hess', alt: ['Hess'], type: 'recall' },
    { q: 'What is the key evidence for seafloor spreading from the ocean floor?', a: 'symmetric magnetic stripe patterns on either side of mid-ocean ridges', alt: ['magnetic striping', 'magnetic reversals'], type: 'concept' },
    { q: 'How does seafloor age relate to distance from a mid-ocean ridge?', a: 'oceanic crust is youngest at the ridge and oldest near continents', alt: ['older farther from ridge'], type: 'concept' },
    { q: 'What happens to old oceanic crust at subduction zones?', a: 'it is recycled back into the mantle', alt: ['subducted into mantle', 'returns to mantle'], type: 'recall' },
    { q: 'Why is the oldest oceanic crust only about 200 million years old?', a: 'because oceanic crust is continuously created and destroyed through spreading and subduction', alt: ['subduction recycles it'], type: 'concept' },
    { q: 'Paleomagnetism in ocean floor basalt records what?', a: 'reversals of Earth\'s magnetic field over time', alt: ['magnetic field reversals', 'geomagnetic reversals'], type: 'recall' },
  ]},
  'hotspots-mantle-plumes': { questions: [
    { q: 'What is a mantle plume?', a: 'a column of abnormally hot rock rising from deep in the mantle', alt: ['hot rising column of mantle rock'], type: 'recall' },
    { q: 'The Hawaiian Islands formed from what geological process?', a: 'a tectonic plate moving over a stationary mantle hotspot', alt: ['hotspot volcanism', 'plate moving over hotspot'], type: 'concept' },
    { q: 'How do hotspot tracks help determine plate motion?', a: 'the chain of volcanic islands shows the direction and speed of plate movement', alt: ['island chain shows plate direction'], type: 'application' },
    { q: 'Yellowstone is an example of what?', a: 'a continental hotspot with a large magma chamber beneath it', alt: ['continental hotspot', 'hotspot under a continent'], type: 'application' },
    { q: 'Why are hotspot volcanoes not found at plate boundaries?', a: 'they are caused by plumes rising from deep mantle independent of plate boundary processes', alt: ['they come from deep mantle not boundaries'], type: 'concept' },
    { q: 'What happens to volcanic islands as they move away from a hotspot?', a: 'they cool, subside, erode, and may become seamounts or atolls', alt: ['they sink and erode'], type: 'concept' },
  ]},
  'geologic-time-scale': { questions: [
    { q: 'What are the four eons in order from oldest to youngest?', a: 'Hadean, Archean, Proterozoic, Phanerozoic', alt: ['hadean archean proterozoic phanerozoic'], type: 'recall' },
    { q: 'The Phanerozoic eon is divided into what three eras?', a: 'Paleozoic, Mesozoic, Cenozoic', alt: ['paleozoic mesozoic cenozoic'], type: 'recall' },
    { q: 'Radiometric dating measures what to determine rock age?', a: 'the ratio of parent to daughter isotopes', alt: ['radioactive decay of isotopes', 'parent daughter isotope ratio'], type: 'concept' },
    { q: 'The principle of superposition states what?', a: 'in undisturbed rock layers, the oldest layers are at the bottom', alt: ['older rocks on bottom'], type: 'recall' },
    { q: 'Index fossils are useful for dating because they what?', a: 'existed for a short time period but were widespread geographically', alt: ['short lived widespread organisms'], type: 'concept' },
    { q: 'What major event marks the boundary between the Mesozoic and Cenozoic eras?', a: 'the mass extinction that wiped out the dinosaurs (K-Pg extinction)', alt: ['dinosaur extinction', 'asteroid impact extinction', 'K-Pg boundary'], type: 'recall' },
  ]},

  // ===== Mineralogy =====
  'rock-cycle': { questions: [
    { q: 'What are the three main types of rocks?', a: 'igneous, sedimentary, and metamorphic', alt: ['igneous sedimentary metamorphic'], type: 'recall' },
    { q: 'How do igneous rocks form?', a: 'from the cooling and crystallization of magma or lava', alt: ['magma cooling', 'lava solidifying'], type: 'recall' },
    { q: 'What processes transform sedimentary rock into metamorphic rock?', a: 'heat and pressure', alt: ['heat pressure', 'temperature and pressure'], type: 'recall' },
    { q: 'Intrusive igneous rocks cool slowly and have what texture?', a: 'coarse-grained (large crystals)', alt: ['coarse grained', 'large crystals', 'phaneritic'], type: 'concept' },
    { q: 'What process converts sediments into sedimentary rock?', a: 'compaction and cementation (lithification)', alt: ['lithification', 'compaction and cementation'], type: 'recall' },
    { q: 'Can any rock type transform into any other rock type?', a: 'yes, the rock cycle shows all rock types can convert to any other through various processes', alt: ['yes all conversions are possible'], type: 'concept' },
  ]},
  'mineral-identification': { questions: [
    { q: 'What is the Mohs hardness scale used for?', a: 'ranking the relative hardness of minerals from 1 (talc) to 10 (diamond)', alt: ['measuring mineral hardness'], type: 'recall' },
    { q: 'What is the difference between a mineral\'s color and its streak?', a: 'streak is the color of the powdered mineral on an unglazed porcelain plate and is more reliable than surface color', alt: ['streak is powder color and more reliable'], type: 'concept' },
    { q: 'What is cleavage in mineralogy?', a: 'the tendency of a mineral to break along flat planes of weakness', alt: ['breaking along flat planes'], type: 'recall' },
    { q: 'What mineral is the most abundant in Earth\'s crust?', a: 'feldspar', alt: ['feldspars'], type: 'recall' },
    { q: 'Luster describes what property of a mineral?', a: 'how light reflects from its surface (metallic vs non-metallic)', alt: ['how it reflects light', 'shininess'], type: 'recall' },
    { q: 'Quartz has what type of fracture?', a: 'conchoidal (curved, shell-like) fracture', alt: ['conchoidal', 'conchoidal fracture'], type: 'recall' },
  ]},
  'weathering-erosion': { questions: [
    { q: 'What is the difference between weathering and erosion?', a: 'weathering breaks down rock in place; erosion transports the material', alt: ['weathering breaks rock erosion moves it'], type: 'concept' },
    { q: 'Frost wedging is an example of what type of weathering?', a: 'mechanical (physical) weathering', alt: ['physical weathering', 'mechanical weathering'], type: 'recall' },
    { q: 'How does carbonic acid contribute to chemical weathering?', a: 'it dissolves limestone and other carbonate rocks', alt: ['dissolves limestone', 'dissolves carbonate rocks'], type: 'concept' },
    { q: 'What is the main agent of erosion on Earth?', a: 'water (running water)', alt: ['water', 'running water', 'rivers'], type: 'recall' },
    { q: 'Root wedging is caused by what?', a: 'plant roots growing into cracks in rock and expanding them', alt: ['plant roots in rock cracks'], type: 'recall' },
    { q: 'Oxidation weathering produces what characteristic color?', a: 'reddish-brown (rust) from iron oxide formation', alt: ['red', 'rust color', 'reddish brown'], type: 'concept' },
  ]},
  'soil-science': { questions: [
    { q: 'What are the main components of soil?', a: 'mineral particles, organic matter, water, and air', alt: ['minerals organic matter water air'], type: 'recall' },
    { q: 'The O horizon of a soil profile contains what?', a: 'organic material such as leaf litter and humus', alt: ['organic matter', 'leaf litter', 'humus'], type: 'recall' },
    { q: 'What is the A horizon commonly known as?', a: 'topsoil', alt: ['top soil'], type: 'recall' },
    { q: 'Soil texture is determined by the proportions of what?', a: 'sand, silt, and clay', alt: ['sand silt clay'], type: 'recall' },
    { q: 'Why is soil considered a nonrenewable resource on human timescales?', a: 'it takes hundreds to thousands of years to form just a few centimeters', alt: ['takes very long to form', 'forms extremely slowly'], type: 'concept' },
    { q: 'What role do decomposers play in soil formation?', a: 'they break down organic matter into humus and release nutrients', alt: ['break down organic matter', 'create humus'], type: 'concept' },
  ]},
  'resource-extraction': { questions: [
    { q: 'What is the difference between a mineral resource and an ore?', a: 'an ore is a mineral deposit that can be mined profitably', alt: ['ore is economically mineable'], type: 'concept' },
    { q: 'What environmental impact does mountaintop removal mining cause?', a: 'habitat destruction, water pollution, and landscape alteration', alt: ['destroys habitats and pollutes water'], type: 'concept' },
    { q: 'Rare earth elements are important for what modern technologies?', a: 'electronics, batteries, magnets, and renewable energy systems', alt: ['electronics and batteries', 'technology'], type: 'recall' },
    { q: 'What is acid mine drainage?', a: 'acidic water flowing from mines due to sulfide mineral oxidation', alt: ['acidic runoff from mines'], type: 'recall' },
    { q: 'How does recycling metals reduce environmental impact?', a: 'it reduces the need for mining, saves energy, and decreases waste', alt: ['less mining and less energy'], type: 'concept' },
    { q: 'What is fracking (hydraulic fracturing)?', a: 'injecting high-pressure fluid into rock to extract oil or natural gas', alt: ['injecting fluid to extract oil or gas'], type: 'recall' },
  ]},
  'sedimentary-environments': { questions: [
    { q: 'What is a sedimentary environment (depositional environment)?', a: 'a location where sediment accumulates and the conditions that characterize it', alt: ['where sediments are deposited'], type: 'recall' },
    { q: 'Cross-bedding in sandstone indicates what?', a: 'deposition by wind or water currents', alt: ['wind or water deposition', 'current deposition'], type: 'concept' },
    { q: 'Evaporite deposits form in what type of environment?', a: 'arid environments where water evaporates and dissolved minerals precipitate', alt: ['dry environments', 'evaporation of water'], type: 'concept' },
    { q: 'Graded bedding (fining upward) indicates what?', a: 'decreasing energy in the depositional environment over time', alt: ['decreasing water energy', 'turbidity current'], type: 'concept' },
    { q: 'Fossil coral reefs in the rock record indicate what past environment?', a: 'warm, shallow, clear marine water', alt: ['warm shallow ocean', 'tropical ocean'], type: 'application' },
    { q: 'What type of sedimentary rock forms from biological activity?', a: 'bioclastic (biochemical) sedimentary rock such as limestone from shells', alt: ['biochemical sedimentary rock', 'limestone from organisms'], type: 'recall' },
  ]},

  // ===== Atmospheric Science =====
  'atmosphere-layers': { questions: [
    { q: 'What are the four main layers of the atmosphere from lowest to highest?', a: 'troposphere, stratosphere, mesosphere, thermosphere', alt: ['troposphere stratosphere mesosphere thermosphere'], type: 'recall' },
    { q: 'In which layer does all weather occur?', a: 'troposphere', alt: [], type: 'recall' },
    { q: 'The ozone layer is found in which atmospheric layer?', a: 'stratosphere', alt: [], type: 'recall' },
    { q: 'What happens to temperature in the troposphere as altitude increases?', a: 'temperature decreases', alt: ['it decreases', 'gets colder'], type: 'recall' },
    { q: 'Why does the stratosphere warm with altitude?', a: 'ozone absorbs ultraviolet radiation and converts it to heat', alt: ['ozone absorbs UV', 'UV absorption by ozone'], type: 'concept' },
    { q: 'What is the tropopause?', a: 'the boundary between the troposphere and stratosphere', alt: ['troposphere stratosphere boundary'], type: 'recall' },
  ]},
  'atmospheric-circulation': { questions: [
    { q: 'What are the three main atmospheric circulation cells in each hemisphere?', a: 'Hadley, Ferrel, and Polar cells', alt: ['hadley ferrel polar'], type: 'recall' },
    { q: 'The Coriolis effect causes winds in the Northern Hemisphere to deflect which way?', a: 'to the right', alt: ['right', 'rightward'], type: 'recall' },
    { q: 'What are the trade winds?', a: 'prevailing easterly winds between the equator and 30 degrees latitude', alt: ['easterly winds near equator'], type: 'recall' },
    { q: 'What causes global atmospheric circulation?', a: 'unequal solar heating of Earth\'s surface between the equator and poles', alt: ['differential heating', 'unequal solar heating'], type: 'concept' },
    { q: 'The jet stream is located where in the atmosphere?', a: 'near the tropopause at boundaries between circulation cells', alt: ['upper troposphere', 'tropopause'], type: 'recall' },
    { q: 'What is the Intertropical Convergence Zone (ITCZ)?', a: 'the zone near the equator where trade winds from both hemispheres converge, causing rising air and heavy rain', alt: ['equatorial convergence zone', 'where trade winds meet'], type: 'concept' },
  ]},
  'weather-fronts': { questions: [
    { q: 'What is a cold front?', a: 'the leading edge of a cold air mass advancing into warmer air', alt: ['cold air pushing into warm air'], type: 'recall' },
    { q: 'What type of weather does a warm front typically bring?', a: 'prolonged, steady precipitation over a wide area', alt: ['steady rain', 'prolonged precipitation'], type: 'concept' },
    { q: 'What is an occluded front?', a: 'a front formed when a cold front overtakes a warm front', alt: ['cold front catches warm front'], type: 'recall' },
    { q: 'A stationary front is characterized by what?', a: 'little to no movement of the boundary between air masses', alt: ['front not moving', 'no movement'], type: 'recall' },
    { q: 'What type of clouds and weather are associated with a cold front?', a: 'cumulonimbus clouds with heavy rain, thunderstorms, and rapid clearing', alt: ['thunderstorms', 'heavy rain and storms'], type: 'concept' },
    { q: 'Air pressure typically does what as a storm system approaches?', a: 'decreases (drops)', alt: ['drops', 'falls', 'decreases'], type: 'recall' },
  ]},
  'severe-weather': { questions: [
    { q: 'What atmospheric conditions are needed for a thunderstorm to form?', a: 'moisture, instability (warm air rising), and a lifting mechanism', alt: ['moisture instability and lift'], type: 'concept' },
    { q: 'A tornado forms from what type of storm?', a: 'a supercell thunderstorm with a rotating updraft (mesocyclone)', alt: ['supercell', 'supercell thunderstorm'], type: 'recall' },
    { q: 'The Enhanced Fujita Scale measures what?', a: 'tornado intensity based on damage (EF0-EF5)', alt: ['tornado strength', 'tornado intensity'], type: 'recall' },
    { q: 'What is the difference between a watch and a warning for severe weather?', a: 'a watch means conditions are favorable; a warning means the event is occurring or imminent', alt: ['watch means possible warning means happening'], type: 'concept' },
    { q: 'Lightning is caused by what?', a: 'electrical discharge from charge separation within clouds or between cloud and ground', alt: ['electrical discharge in clouds', 'charge buildup in clouds'], type: 'concept' },
    { q: 'What scale measures hurricane intensity?', a: 'Saffir-Simpson Hurricane Wind Scale (Category 1-5)', alt: ['saffir simpson', 'saffir-simpson scale'], type: 'recall' },
  ]},
  'air-quality-pollution': { questions: [
    { q: 'What are the six criteria air pollutants regulated by the EPA?', a: 'carbon monoxide, lead, nitrogen dioxide, ozone, particulate matter, and sulfur dioxide', alt: ['CO, Pb, NO2, O3, PM, SO2'], type: 'recall' },
    { q: 'What causes smog in urban areas?', a: 'photochemical reactions between nitrogen oxides and volatile organic compounds in sunlight', alt: ['NOx and VOCs in sunlight'], type: 'concept' },
    { q: 'Temperature inversions worsen air quality because they do what?', a: 'trap pollutants near the ground by preventing vertical air mixing', alt: ['trap pollutants near ground'], type: 'concept' },
    { q: 'What is the Air Quality Index (AQI)?', a: 'a numerical scale that communicates how polluted the air is and associated health concerns', alt: ['air pollution health index'], type: 'recall' },
    { q: 'Acid rain is primarily caused by what pollutants?', a: 'sulfur dioxide and nitrogen oxides reacting with water in the atmosphere', alt: ['SO2 and NOx'], type: 'recall' },
    { q: 'Indoor air pollution can be worse than outdoor because of what?', a: 'poor ventilation traps pollutants like radon, VOCs, and combustion byproducts', alt: ['poor ventilation and trapped pollutants'], type: 'concept' },
  ]},
  'ozone-depletion': { questions: [
    { q: 'What chemicals are primarily responsible for ozone depletion?', a: 'chlorofluorocarbons (CFCs)', alt: ['CFCs', 'chlorofluorocarbons'], type: 'recall' },
    { q: 'The Montreal Protocol addressed what environmental issue?', a: 'the phaseout of ozone-depleting substances', alt: ['banning CFCs', 'ozone protection'], type: 'recall' },
    { q: 'Where is the ozone hole most prominent?', a: 'over Antarctica', alt: ['Antarctica', 'south pole'], type: 'recall' },
    { q: 'How do CFCs destroy ozone?', a: 'UV radiation breaks off chlorine atoms which catalytically destroy ozone molecules', alt: ['chlorine from CFCs breaks down ozone'], type: 'concept' },
    { q: 'Why is stratospheric ozone important?', a: 'it absorbs harmful ultraviolet radiation protecting life on Earth', alt: ['blocks UV radiation', 'absorbs UV'], type: 'concept' },
    { q: 'Is the ozone layer recovering?', a: 'yes, slowly recovering due to the Montreal Protocol reducing CFC emissions', alt: ['yes slowly recovering'], type: 'recall' },
  ]},

  // ===== Oceanography =====
  'ocean-currents': { questions: [
    { q: 'What are the two main types of ocean currents?', a: 'surface currents driven by wind and deep currents driven by density differences', alt: ['surface and deep currents'], type: 'recall' },
    { q: 'The Gulf Stream is important because it does what?', a: 'transports warm water northward, moderating the climate of Western Europe', alt: ['warms western europe', 'carries warm water north'], type: 'concept' },
    { q: 'What is upwelling?', a: 'the rising of cold, nutrient-rich water from the deep ocean to the surface', alt: ['cold deep water rising to surface'], type: 'recall' },
    { q: 'How does the Coriolis effect influence ocean currents?', a: 'it causes currents to curve right in the Northern Hemisphere and left in the Southern Hemisphere', alt: ['deflects currents due to earth rotation'], type: 'concept' },
    { q: 'What is a gyre?', a: 'a large circular system of ocean currents caused by wind patterns and the Coriolis effect', alt: ['large circular ocean current'], type: 'recall' },
    { q: 'El Nino involves what change in the Pacific Ocean?', a: 'weakening of trade winds and warming of eastern Pacific surface waters', alt: ['warming of eastern pacific', 'weak trade winds warm water east pacific'], type: 'concept' },
  ]},
  'tides': { questions: [
    { q: 'What primarily causes ocean tides?', a: 'the gravitational pull of the Moon and Sun on Earth\'s oceans', alt: ['moon and sun gravity', 'gravitational pull of moon'], type: 'recall' },
    { q: 'How many high tides typically occur in a 24-hour period?', a: 'two', alt: ['2'], type: 'recall' },
    { q: 'Spring tides occur when the Sun, Moon, and Earth are in what alignment?', a: 'aligned in a straight line (syzygy) during new and full moons', alt: ['aligned', 'in a line', 'new or full moon'], type: 'concept' },
    { q: 'Neap tides produce what type of tidal range?', a: 'smaller tidal range because the Sun and Moon are at right angles', alt: ['smaller tides', 'low tidal range'], type: 'concept' },
    { q: 'Why are there tidal bulges on opposite sides of Earth?', a: 'gravitational attraction on the near side and inertia on the far side', alt: ['gravity near side inertia far side'], type: 'concept' },
    { q: 'What is a tidal bore?', a: 'a wave that travels up a river or narrow bay as the tide comes in', alt: ['tidal wave moving up river'], type: 'recall' },
  ]},
  'ocean-chemistry': { questions: [
    { q: 'What is the average salinity of ocean water?', a: 'approximately 35 parts per thousand (3.5%)', alt: ['35 ppt', '3.5 percent', '35 parts per thousand'], type: 'recall' },
    { q: 'What two ions make up most of the dissolved salts in seawater?', a: 'sodium and chloride', alt: ['Na and Cl', 'sodium chloride'], type: 'recall' },
    { q: 'What is the thermocline?', a: 'the layer of ocean where temperature changes rapidly with depth', alt: ['rapid temperature change layer'], type: 'recall' },
    { q: 'How does ocean water absorb carbon dioxide?', a: 'CO2 dissolves at the surface and reacts with water to form carbonic acid', alt: ['CO2 dissolves and forms carbonic acid'], type: 'concept' },
    { q: 'What is ocean stratification?', a: 'layering of ocean water by density, temperature, and salinity', alt: ['layers of different density water'], type: 'recall' },
    { q: 'How does salinity affect water density?', a: 'higher salinity increases water density', alt: ['more salt means denser water'], type: 'concept' },
  ]},
  'marine-ecosystems': { questions: [
    { q: 'What are phytoplankton and why are they important?', a: 'microscopic photosynthetic organisms that produce roughly half of Earth\'s oxygen', alt: ['tiny ocean plants that make oxygen'], type: 'concept' },
    { q: 'What is a coral reef?', a: 'a marine ecosystem built by colonies of coral polyps secreting calcium carbonate', alt: ['calcium carbonate structure built by corals'], type: 'recall' },
    { q: 'What ocean zone receives enough light for photosynthesis?', a: 'the photic (euphotic) zone, roughly the top 200 meters', alt: ['photic zone', 'euphotic zone'], type: 'recall' },
    { q: 'What are hydrothermal vents?', a: 'openings in the seafloor where geothermally heated water exits, supporting chemosynthetic ecosystems', alt: ['hot water vents on ocean floor'], type: 'recall' },
    { q: 'Coral bleaching is caused by what?', a: 'loss of symbiotic algae (zooxanthellae) due to stress such as elevated water temperatures', alt: ['warm water killing algae in coral', 'loss of zooxanthellae'], type: 'concept' },
    { q: 'Estuaries are ecologically important because they do what?', a: 'serve as nurseries for many marine species where freshwater meets saltwater', alt: ['nursery habitats where fresh and salt water mix'], type: 'concept' },
  ]},
  'ocean-acidification': { questions: [
    { q: 'What causes ocean acidification?', a: 'increased absorption of atmospheric CO2 which forms carbonic acid', alt: ['CO2 dissolving in ocean'], type: 'recall' },
    { q: 'Ocean acidification harms shell-building organisms because it does what?', a: 'reduces carbonate ion availability needed for building calcium carbonate shells', alt: ['less carbonate for shells'], type: 'concept' },
    { q: 'Ocean pH has dropped by approximately how much since the Industrial Revolution?', a: 'about 0.1 pH units (from 8.2 to 8.1)', alt: ['0.1 pH units'], type: 'recall' },
    { q: 'Why is even a small change in ocean pH significant?', a: 'the pH scale is logarithmic so 0.1 units represents about a 30% increase in acidity', alt: ['logarithmic scale means big change in hydrogen ions'], type: 'concept' },
    { q: 'Which marine organisms are most vulnerable to acidification?', a: 'calcifying organisms like corals, mollusks, and some plankton', alt: ['corals and shellfish', 'organisms with calcium carbonate shells'], type: 'concept' },
    { q: 'How does ocean acidification interact with climate change?', a: 'both are driven by increased CO2 and together threaten marine ecosystems through warming and chemical stress', alt: ['both caused by CO2 both harm ocean life'], type: 'concept' },
  ]},
  'thermohaline-circulation': { questions: [
    { q: 'What drives thermohaline circulation?', a: 'differences in water density caused by temperature and salinity variations', alt: ['density differences from temperature and salinity'], type: 'recall' },
    { q: 'Where does deep water formation primarily occur?', a: 'in the North Atlantic and around Antarctica where cold salty water sinks', alt: ['north atlantic and antarctica'], type: 'recall' },
    { q: 'The thermohaline circulation is sometimes called what?', a: 'the global conveyor belt', alt: ['conveyor belt', 'ocean conveyor belt'], type: 'recall' },
    { q: 'How could melting Arctic ice affect thermohaline circulation?', a: 'freshwater input could reduce salinity and prevent deep water formation, potentially slowing circulation', alt: ['freshwater could slow it down'], type: 'concept' },
    { q: 'How long does it take water to complete one full cycle of the conveyor belt?', a: 'approximately 1000 years', alt: ['about 1000 years', '1000 years'], type: 'recall' },
    { q: 'Why is thermohaline circulation important for global climate?', a: 'it redistributes heat from the tropics to higher latitudes and drives nutrient cycling', alt: ['moves heat around the globe'], type: 'concept' },
  ]},

  // ===== Climate Change =====
  'greenhouse-effect': { questions: [
    { q: 'What is the greenhouse effect?', a: 'the trapping of heat in the atmosphere by greenhouse gases that absorb and re-emit infrared radiation', alt: ['gases trap heat in atmosphere'], type: 'recall' },
    { q: 'Name three major greenhouse gases.', a: 'carbon dioxide, methane, and water vapor', alt: ['CO2 methane water vapor', 'carbon dioxide methane nitrous oxide'], type: 'recall' },
    { q: 'Why is the greenhouse effect essential for life on Earth?', a: 'without it, Earth\'s average temperature would be about -18C instead of +15C', alt: ['keeps earth warm enough for life'], type: 'concept' },
    { q: 'How does increasing CO2 enhance the greenhouse effect?', a: 'more CO2 absorbs and re-emits more infrared radiation, increasing atmospheric temperature', alt: ['more CO2 traps more heat'], type: 'concept' },
    { q: 'Methane is a more potent greenhouse gas than CO2 because it what?', a: 'absorbs more infrared radiation per molecule, though it persists for less time', alt: ['traps more heat per molecule'], type: 'concept' },
    { q: 'What is the difference between the natural and enhanced greenhouse effect?', a: 'the enhanced effect is the additional warming from human-produced greenhouse gas emissions above natural levels', alt: ['enhanced is extra warming from human emissions'], type: 'concept' },
  ]},
  'paleoclimate': { questions: [
    { q: 'What are ice cores used for in climate science?', a: 'analyzing trapped air bubbles to reconstruct past atmospheric composition and temperature', alt: ['studying past climate from trapped air'], type: 'concept' },
    { q: 'What are Milankovitch cycles?', a: 'variations in Earth\'s orbital eccentricity, axial tilt, and precession that affect long-term climate', alt: ['orbital variations affecting climate'], type: 'recall' },
    { q: 'Tree rings (dendrochronology) provide what climate information?', a: 'annual records of temperature and precipitation based on ring width', alt: ['past temperature and rainfall from ring width'], type: 'concept' },
    { q: 'What proxy data do ocean sediment cores provide?', a: 'past ocean temperature and chemistry from fossilized organisms like foraminifera', alt: ['past ocean conditions from fossils'], type: 'concept' },
    { q: 'During ice ages, sea levels were lower because why?', a: 'more water was stored in continental ice sheets', alt: ['water locked in ice sheets', 'water frozen in glaciers'], type: 'concept' },
    { q: 'Current CO2 levels compared to the past 800,000 years are what?', a: 'higher than at any point in that record', alt: ['highest in 800000 years', 'unprecedented'], type: 'recall' },
  ]},
  'climate-models': { questions: [
    { q: 'What is a climate model?', a: 'a computer simulation that uses mathematical equations to represent interactions of the atmosphere, oceans, land, and ice', alt: ['computer simulation of climate system'], type: 'recall' },
    { q: 'What are emission scenarios (RCPs or SSPs)?', a: 'projected pathways of greenhouse gas concentrations used as inputs for climate models', alt: ['future emission pathways for models'], type: 'concept' },
    { q: 'Why do climate models show a range of temperature projections?', a: 'because of different emission scenarios and uncertainties in climate sensitivity', alt: ['different scenarios and uncertainties'], type: 'concept' },
    { q: 'How are climate models validated?', a: 'by comparing model outputs to observed historical climate data (hindcasting)', alt: ['comparing predictions to past data'], type: 'concept' },
    { q: 'What is climate sensitivity?', a: 'the amount of global warming expected from a doubling of atmospheric CO2', alt: ['warming from doubling CO2'], type: 'recall' },
    { q: 'What is the difference between weather forecasting and climate modeling?', a: 'weather predicts short-term conditions; climate models project long-term statistical trends', alt: ['weather is short term climate is long term'], type: 'concept' },
  ]},
  'mitigation-adaptation': { questions: [
    { q: 'What is the difference between climate mitigation and adaptation?', a: 'mitigation reduces greenhouse gas emissions; adaptation adjusts to climate impacts', alt: ['mitigation reduces cause adaptation adjusts to effects'], type: 'concept' },
    { q: 'Name two examples of climate mitigation strategies.', a: 'transitioning to renewable energy and improving energy efficiency', alt: ['renewable energy and efficiency', 'solar power and insulation'], type: 'recall' },
    { q: 'What is carbon sequestration?', a: 'the capture and long-term storage of atmospheric carbon dioxide', alt: ['capturing and storing CO2'], type: 'recall' },
    { q: 'How do rising sea levels exemplify the need for adaptation?', a: 'coastal communities must build sea walls, relocate, or develop flood management', alt: ['coastal areas must prepare for flooding'], type: 'application' },
    { q: 'What role do forests play in climate mitigation?', a: 'they act as carbon sinks by absorbing CO2 through photosynthesis', alt: ['absorb CO2', 'carbon sinks'], type: 'concept' },
    { q: 'What is the Paris Agreement\'s main goal?', a: 'to limit global warming to well below 2 degrees Celsius above pre-industrial levels', alt: ['limit warming below 2 degrees', 'keep warming under 2C'], type: 'recall' },
  ]},
  'carbon-cycle-feedbacks': { questions: [
    { q: 'What is a positive feedback loop in the climate system?', a: 'a process where the output amplifies the original change (e.g., warming causes more warming)', alt: ['amplifying loop', 'change reinforces itself'], type: 'concept' },
    { q: 'The ice-albedo feedback works how?', a: 'melting ice exposes darker surfaces that absorb more heat, causing further melting', alt: ['less ice means more heat absorbed means more melting'], type: 'concept' },
    { q: 'What is the permafrost feedback concern?', a: 'thawing permafrost releases methane and CO2, amplifying warming', alt: ['melting permafrost releases greenhouse gases'], type: 'concept' },
    { q: 'How do oceans act as both a carbon sink and potential feedback?', a: 'oceans absorb CO2 but warmer oceans absorb less, potentially releasing stored CO2', alt: ['warm oceans absorb less CO2'], type: 'concept' },
    { q: 'What is a tipping point in the climate system?', a: 'a threshold beyond which change becomes self-reinforcing and potentially irreversible', alt: ['point of no return', 'irreversible threshold'], type: 'concept' },
    { q: 'Water vapor feedback amplifies warming because what?', a: 'warmer air holds more water vapor which is itself a greenhouse gas', alt: ['more evaporation means more greenhouse effect'], type: 'concept' },
  ]},
  'climate-policy': { questions: [
    { q: 'What is a carbon tax?', a: 'a fee charged per unit of carbon dioxide emissions to discourage fossil fuel use', alt: ['tax on CO2 emissions'], type: 'recall' },
    { q: 'What is cap-and-trade?', a: 'a system that sets a total emissions limit and allows companies to trade emission permits', alt: ['emissions trading system', 'pollution permits market'], type: 'recall' },
    { q: 'What role does the IPCC play in climate policy?', a: 'it assesses climate science and provides reports that inform international policy decisions', alt: ['provides scientific assessments for policy'], type: 'recall' },
    { q: 'Why is international cooperation essential for addressing climate change?', a: 'greenhouse gases mix globally so emissions from any country affect the entire planet', alt: ['climate change is a global problem'], type: 'concept' },
    { q: 'What is climate justice?', a: 'addressing the disproportionate impact of climate change on vulnerable and low-income communities', alt: ['fairness in climate impacts and solutions'], type: 'concept' },
    { q: 'What are Nationally Determined Contributions (NDCs)?', a: 'each country\'s self-set climate action plan under the Paris Agreement', alt: ['country climate pledges under Paris Agreement'], type: 'recall' },
  ]},

  // ===== Astronomy =====
  'stellar-evolution': { questions: [
    { q: 'What is a nebula in the context of star formation?', a: 'a cloud of gas and dust from which stars form through gravitational collapse', alt: ['gas and dust cloud where stars form'], type: 'recall' },
    { q: 'What process powers a main sequence star?', a: 'nuclear fusion of hydrogen into helium in the core', alt: ['hydrogen fusion', 'nuclear fusion'], type: 'recall' },
    { q: 'What determines whether a star becomes a white dwarf, neutron star, or black hole?', a: 'the mass of the star', alt: ['its mass', 'stellar mass'], type: 'concept' },
    { q: 'A red giant forms when what happens?', a: 'a star exhausts hydrogen in its core and begins fusing hydrogen in a shell, causing the outer layers to expand', alt: ['core hydrogen runs out outer layers expand'], type: 'concept' },
    { q: 'What is a supernova?', a: 'the explosive death of a massive star when its core collapses', alt: ['exploding massive star', 'star explosion'], type: 'recall' },
    { q: 'What elements are created in supernovae?', a: 'elements heavier than iron through rapid neutron capture', alt: ['heavy elements beyond iron'], type: 'concept' },
  ]},
  'hr-diagram': { questions: [
    { q: 'What two properties does the Hertzsprung-Russell diagram plot?', a: 'luminosity (or absolute magnitude) versus temperature (or spectral class)', alt: ['brightness vs temperature', 'luminosity vs temperature'], type: 'recall' },
    { q: 'Where do main sequence stars fall on the HR diagram?', a: 'along a diagonal band from hot bright upper-left to cool dim lower-right', alt: ['diagonal band upper left to lower right'], type: 'recall' },
    { q: 'Where are red giants located on the HR diagram?', a: 'upper right (cool but very luminous)', alt: ['upper right'], type: 'recall' },
    { q: 'Where are white dwarfs located on the HR diagram?', a: 'lower left (hot but very dim)', alt: ['lower left'], type: 'recall' },
    { q: 'What does a star\'s position on the main sequence tell you?', a: 'its mass, temperature, luminosity, and approximate lifespan', alt: ['mass and lifespan'], type: 'concept' },
    { q: 'Hotter stars appear what color?', a: 'blue or blue-white', alt: ['blue', 'blue-white'], type: 'recall' },
  ]},
  'solar-system': { questions: [
    { q: 'What are the four inner (terrestrial) planets?', a: 'Mercury, Venus, Earth, and Mars', alt: ['mercury venus earth mars'], type: 'recall' },
    { q: 'What are the four outer (gas/ice giant) planets?', a: 'Jupiter, Saturn, Uranus, and Neptune', alt: ['jupiter saturn uranus neptune'], type: 'recall' },
    { q: 'What is the asteroid belt located between?', a: 'Mars and Jupiter', alt: ['mars and jupiter'], type: 'recall' },
    { q: 'What is the Kuiper Belt?', a: 'a region of icy bodies beyond Neptune\'s orbit, including Pluto', alt: ['icy objects beyond neptune'], type: 'recall' },
    { q: 'How did the solar system form?', a: 'from the gravitational collapse of a rotating cloud of gas and dust (solar nebula)', alt: ['from a collapsing nebula', 'solar nebula collapse'], type: 'concept' },
    { q: 'What distinguishes terrestrial planets from gas giants?', a: 'terrestrial planets are small, rocky, and dense; gas giants are large with thick gaseous atmospheres', alt: ['rocky vs gaseous'], type: 'concept' },
  ]},
  'cosmology': { questions: [
    { q: 'What is the Big Bang theory?', a: 'the theory that the universe began from a hot dense state approximately 13.8 billion years ago and has been expanding since', alt: ['universe started as hot dense point and expanded'], type: 'recall' },
    { q: 'What evidence supports the Big Bang?', a: 'cosmic microwave background radiation, redshift of galaxies, and the abundance of light elements', alt: ['CMB radiation and galaxy redshift'], type: 'concept' },
    { q: 'What is Hubble\'s Law?', a: 'galaxies are moving away from us at speeds proportional to their distance', alt: ['farther galaxies move faster', 'velocity proportional to distance'], type: 'recall' },
    { q: 'What is dark matter?', a: 'invisible matter that does not emit light but exerts gravitational influence on visible matter', alt: ['unseen matter with gravitational effects'], type: 'recall' },
    { q: 'What is dark energy?', a: 'a mysterious force causing the accelerating expansion of the universe', alt: ['force accelerating universe expansion'], type: 'recall' },
    { q: 'What is redshift?', a: 'the stretching of light wavelengths from objects moving away, shifting toward the red end of the spectrum', alt: ['light wavelength lengthening from receding objects'], type: 'concept' },
  ]},
  'spectroscopy': { questions: [
    { q: 'What is spectroscopy in astronomy?', a: 'the analysis of light spectra to determine the composition, temperature, and motion of celestial objects', alt: ['studying light to learn about stars'], type: 'recall' },
    { q: 'Absorption lines in a star\'s spectrum indicate what?', a: 'elements in the star\'s atmosphere that absorb specific wavelengths', alt: ['elements absorbing specific wavelengths'], type: 'concept' },
    { q: 'How is the Doppler effect used in spectroscopy?', a: 'shifted spectral lines reveal whether an object is moving toward (blueshift) or away (redshift)', alt: ['spectral shifts show motion'], type: 'concept' },
    { q: 'What does a continuous spectrum look like?', a: 'an unbroken band of colors with no gaps, produced by a hot dense object', alt: ['rainbow with no gaps'], type: 'recall' },
    { q: 'An emission spectrum contains what?', a: 'bright lines at specific wavelengths produced by excited gas', alt: ['bright lines from hot gas'], type: 'recall' },
    { q: 'How can spectroscopy determine a star\'s composition?', a: 'each element produces a unique pattern of spectral lines', alt: ['unique spectral fingerprint for each element'], type: 'concept' },
  ]},
  'galactic-structure': { questions: [
    { q: 'What type of galaxy is the Milky Way?', a: 'a barred spiral galaxy', alt: ['barred spiral'], type: 'recall' },
    { q: 'What is at the center of most large galaxies?', a: 'a supermassive black hole', alt: ['supermassive black hole'], type: 'recall' },
    { q: 'What are the three main galaxy types?', a: 'spiral, elliptical, and irregular', alt: ['spiral elliptical irregular'], type: 'recall' },
    { q: 'What is the Local Group?', a: 'the cluster of galaxies that includes the Milky Way and Andromeda', alt: ['our galaxy cluster'], type: 'recall' },
    { q: 'What evidence suggests dark matter exists in galaxies?', a: 'galaxy rotation curves show stars orbit faster than visible mass predicts', alt: ['rotation curves dont match visible mass'], type: 'concept' },
    { q: 'What is a galaxy cluster?', a: 'a gravitationally bound group of hundreds to thousands of galaxies', alt: ['group of many galaxies held by gravity'], type: 'recall' },
  ]},

  // ===== Space Exploration =====
  'telescopes-instruments': { questions: [
    { q: 'What is the difference between a refracting and reflecting telescope?', a: 'refractors use lenses to bend light; reflectors use mirrors to gather light', alt: ['lenses vs mirrors'], type: 'recall' },
    { q: 'Why are space telescopes advantageous over ground-based ones?', a: 'they avoid atmospheric distortion and can observe wavelengths blocked by the atmosphere', alt: ['no atmosphere interference'], type: 'concept' },
    { q: 'What does the James Webb Space Telescope primarily observe?', a: 'infrared light to study early galaxies, star formation, and exoplanet atmospheres', alt: ['infrared light'], type: 'recall' },
    { q: 'What is a radio telescope used for?', a: 'detecting radio waves from celestial objects like pulsars, galaxies, and cosmic background radiation', alt: ['detecting radio waves from space'], type: 'recall' },
    { q: 'What is adaptive optics?', a: 'technology that corrects for atmospheric turbulence in real-time to sharpen telescope images', alt: ['correcting atmospheric distortion'], type: 'recall' },
    { q: 'What is light-gathering power and why does it matter?', a: 'the ability of a telescope to collect light based on mirror/lens area; larger means fainter objects visible', alt: ['bigger mirror collects more light sees fainter objects'], type: 'concept' },
  ]},
  'space-missions': { questions: [
    { q: 'What was the Apollo 11 mission\'s achievement?', a: 'the first crewed Moon landing in 1969', alt: ['first moon landing', 'first humans on moon'], type: 'recall' },
    { q: 'What is the International Space Station (ISS)?', a: 'a multinational research laboratory orbiting Earth', alt: ['space station orbiting earth'], type: 'recall' },
    { q: 'What did the Voyager missions accomplish?', a: 'explored the outer planets and became the first human-made objects to enter interstellar space', alt: ['explored outer planets reached interstellar space'], type: 'recall' },
    { q: 'What is the purpose of the Mars rovers?', a: 'to explore the Martian surface, study geology, search for signs of past water and life', alt: ['explore mars look for water and life'], type: 'recall' },
    { q: 'What is the Hubble Space Telescope known for?', a: 'transforming our understanding of the universe through deep-space visible and UV/IR observations', alt: ['deep space observations', 'space telescope photos'], type: 'recall' },
    { q: 'What is a gravity assist (slingshot maneuver)?', a: 'using a planet\'s gravity to accelerate or redirect a spacecraft without using fuel', alt: ['using planet gravity to speed up spacecraft'], type: 'concept' },
  ]},
  'exoplanets': { questions: [
    { q: 'What is an exoplanet?', a: 'a planet that orbits a star outside our solar system', alt: ['planet around another star'], type: 'recall' },
    { q: 'How does the transit method detect exoplanets?', a: 'by measuring the slight dimming of a star\'s light as a planet passes in front of it', alt: ['star dims when planet crosses in front'], type: 'concept' },
    { q: 'What is the radial velocity method?', a: 'detecting the wobble of a star caused by gravitational pull of an orbiting planet', alt: ['star wobble from planet gravity'], type: 'concept' },
    { q: 'What is the habitable zone?', a: 'the range of distances from a star where liquid water could exist on a planet\'s surface', alt: ['goldilocks zone', 'zone where liquid water possible'], type: 'recall' },
    { q: 'The Kepler Space Telescope discovered what?', a: 'thousands of exoplanets, showing planets are common in the galaxy', alt: ['thousands of exoplanets'], type: 'recall' },
    { q: 'What is a hot Jupiter?', a: 'a gas giant exoplanet orbiting very close to its star with a short orbital period', alt: ['gas giant very close to star'], type: 'recall' },
  ]},
  'habitability': { questions: [
    { q: 'What conditions are considered necessary for life as we know it?', a: 'liquid water, energy source, and essential chemical elements (carbon, hydrogen, nitrogen, oxygen, phosphorus, sulfur)', alt: ['water energy and CHNOPS elements'], type: 'concept' },
    { q: 'Why is Mars considered a candidate for past life?', a: 'evidence of ancient liquid water, a past atmosphere, and organic molecules detected', alt: ['had water in past', 'evidence of past water'], type: 'concept' },
    { q: 'What makes Europa (Jupiter\'s moon) interesting for habitability?', a: 'it has a subsurface liquid water ocean beneath its ice shell', alt: ['ocean under ice'], type: 'recall' },
    { q: 'What is the Drake Equation used for?', a: 'estimating the number of communicative civilizations in the Milky Way', alt: ['estimating intelligent civilizations'], type: 'recall' },
    { q: 'What does SETI stand for and do?', a: 'Search for Extraterrestrial Intelligence; it scans for signals from other civilizations', alt: ['search for extraterrestrial intelligence'], type: 'recall' },
    { q: 'Enceladus (Saturn\'s moon) is a habitability candidate because of what?', a: 'geysers of water vapor suggesting a subsurface ocean with potential hydrothermal activity', alt: ['water geysers and subsurface ocean'], type: 'concept' },
  ]},
  'astrobiology': { questions: [
    { q: 'What is astrobiology?', a: 'the study of the origin, evolution, and distribution of life in the universe', alt: ['study of life in the universe'], type: 'recall' },
    { q: 'Extremophiles are important for astrobiology because they what?', a: 'show that life can thrive in extreme conditions similar to those on other worlds', alt: ['life survives extreme conditions like other planets'], type: 'concept' },
    { q: 'What are biosignatures?', a: 'detectable indicators of life such as specific gases, chemical patterns, or structures', alt: ['signs of life like certain gases'], type: 'recall' },
    { q: 'How could we detect life on an exoplanet?', a: 'by analyzing its atmosphere for biosignature gases like oxygen and methane using spectroscopy', alt: ['atmospheric spectroscopy for biosignatures'], type: 'concept' },
    { q: 'What is panspermia?', a: 'the hypothesis that life or its precursors can be transported between worlds via meteorites', alt: ['life traveling between planets on rocks'], type: 'recall' },
    { q: 'Why is the discovery of organic molecules on Mars significant?', a: 'organic molecules are building blocks of life though they can also form abiotically', alt: ['building blocks of life found on mars'], type: 'concept' },
  ]},
  'space-resource-utilization': { questions: [
    { q: 'What is In-Situ Resource Utilization (ISRU)?', a: 'using materials found at a destination (like Mars) to support missions instead of bringing everything from Earth', alt: ['using local resources in space'], type: 'recall' },
    { q: 'Lunar regolith could be used for what?', a: 'construction material, extracting oxygen, and radiation shielding', alt: ['building and oxygen extraction'], type: 'concept' },
    { q: 'Why is water ice on the Moon important for space exploration?', a: 'it can provide drinking water, oxygen for breathing, and hydrogen/oxygen for rocket fuel', alt: ['water fuel and oxygen'], type: 'concept' },
    { q: 'What is asteroid mining?', a: 'extracting valuable minerals and resources from asteroids', alt: ['mining asteroids for resources'], type: 'recall' },
    { q: 'How could Mars\'s atmosphere be used as a resource?', a: 'CO2 can be converted into oxygen and fuel through chemical processes like the Sabatier reaction', alt: ['convert CO2 to oxygen and fuel'], type: 'concept' },
    { q: 'What is the Outer Space Treaty\'s stance on resource extraction?', a: 'space is the province of all mankind; no nation can claim sovereignty but resource use policies are evolving', alt: ['no sovereignty but resource rules developing'], type: 'recall' },
  ]},

  // ===== Natural Hazards =====
  'earthquakes': { questions: [
    { q: 'What causes most earthquakes?', a: 'sudden release of energy from movement along faults at plate boundaries', alt: ['fault movement', 'plate boundary movement'], type: 'recall' },
    { q: 'What is the difference between the epicenter and the focus (hypocenter)?', a: 'the focus is the underground point of rupture; the epicenter is the point on the surface directly above it', alt: ['focus is underground epicenter is above on surface'], type: 'recall' },
    { q: 'The Richter and moment magnitude scales measure what?', a: 'earthquake magnitude (energy released)', alt: ['earthquake strength', 'earthquake energy'], type: 'recall' },
    { q: 'Why is the moment magnitude scale logarithmic?', a: 'each whole number increase represents about 32 times more energy released', alt: ['each number is 32x more energy'], type: 'concept' },
    { q: 'What is liquefaction?', a: 'when saturated soil loses strength during shaking and behaves like a liquid', alt: ['soil becomes liquid during shaking'], type: 'recall' },
    { q: 'How are earthquakes located using seismic stations?', a: 'by triangulation using the arrival time difference between P-waves and S-waves at three or more stations', alt: ['triangulation of p and s wave arrivals'], type: 'concept' },
  ]},
  'volcanic-eruptions': { questions: [
    { q: 'What determines whether a volcanic eruption is explosive or effusive?', a: 'magma viscosity and gas content; high silica magma with more gas is more explosive', alt: ['viscosity and gas content'], type: 'concept' },
    { q: 'What is a pyroclastic flow?', a: 'a fast-moving current of hot gas and volcanic matter that flows down the side of a volcano', alt: ['hot gas and debris flow from volcano'], type: 'recall' },
    { q: 'Shield volcanoes are formed from what type of lava?', a: 'low-viscosity basaltic lava that flows easily and builds broad gentle slopes', alt: ['runny basaltic lava'], type: 'concept' },
    { q: 'What is a lahar?', a: 'a destructive mudflow of volcanic debris and water', alt: ['volcanic mudflow'], type: 'recall' },
    { q: 'How can volcanic eruptions affect global climate?', a: 'sulfur dioxide aerosols reflect sunlight and can cause temporary global cooling', alt: ['aerosols block sunlight cause cooling'], type: 'concept' },
    { q: 'What is the Ring of Fire?', a: 'a zone of frequent earthquakes and volcanic eruptions encircling the Pacific Ocean', alt: ['volcanic zone around pacific ocean'], type: 'recall' },
  ]},
  'hurricanes-tornadoes': { questions: [
    { q: 'What is the energy source for hurricanes?', a: 'warm ocean water evaporation providing latent heat', alt: ['warm ocean water', 'heat from warm water'], type: 'concept' },
    { q: 'What is the eye of a hurricane?', a: 'the calm, clear center of the storm surrounded by the eyewall of intense winds', alt: ['calm center of hurricane'], type: 'recall' },
    { q: 'Why do hurricanes weaken over land?', a: 'they lose their warm water energy source and encounter increased friction', alt: ['no warm water and more friction'], type: 'concept' },
    { q: 'What conditions favor tornado formation?', a: 'warm moist air meeting cool dry air with wind shear creating rotation', alt: ['warm moist and cool dry air with wind shear'], type: 'concept' },
    { q: 'Storm surge is dangerous because it does what?', a: 'pushes a wall of ocean water onshore causing severe coastal flooding', alt: ['ocean water pushed onto land', 'coastal flooding'], type: 'concept' },
    { q: 'In the Northern Hemisphere hurricanes rotate in what direction?', a: 'counterclockwise', alt: ['counter clockwise', 'counter-clockwise'], type: 'recall' },
  ]},
  'hazard-risk-assessment': { questions: [
    { q: 'What is the difference between a hazard and a risk?', a: 'a hazard is a potential danger; risk is the probability of harm considering exposure and vulnerability', alt: ['hazard is danger risk is probability of harm'], type: 'concept' },
    { q: 'What factors increase vulnerability to natural hazards?', a: 'poverty, poor infrastructure, high population density, and lack of early warning systems', alt: ['poverty poor buildings dense population'], type: 'concept' },
    { q: 'What is a hazard map?', a: 'a map showing areas at risk from specific natural hazards based on historical data and modeling', alt: ['map of areas at risk'], type: 'recall' },
    { q: 'How does early warning systems reduce disaster impact?', a: 'they provide time for evacuation and preparation before a hazard strikes', alt: ['gives time to evacuate'], type: 'concept' },
    { q: 'What is the recurrence interval of a natural hazard?', a: 'the average time between events of a given magnitude', alt: ['average time between events'], type: 'recall' },
    { q: 'Why is land-use planning important for hazard mitigation?', a: 'it prevents construction in high-risk zones like floodplains and fault lines', alt: ['keeps people from building in dangerous areas'], type: 'concept' },
  ]},
  'tsunami-science': { questions: [
    { q: 'What causes most tsunamis?', a: 'underwater earthquakes that displace large volumes of water', alt: ['submarine earthquakes', 'undersea earthquakes'], type: 'recall' },
    { q: 'How fast can tsunamis travel in the open ocean?', a: 'up to 800 km/h (500 mph), as fast as a jet plane', alt: ['500 mph', '800 kph'], type: 'recall' },
    { q: 'Why are tsunamis barely noticeable in the open ocean?', a: 'they have long wavelengths and low amplitude in deep water', alt: ['small height in deep water'], type: 'concept' },
    { q: 'What happens to a tsunami as it approaches shallow coastal water?', a: 'it slows down, wavelength decreases, and wave height increases dramatically', alt: ['slows down and gets taller'], type: 'concept' },
    { q: 'What is a tsunami warning system based on?', a: 'seismic monitoring and ocean buoys that detect changes in sea level', alt: ['seismometers and ocean buoys'], type: 'recall' },
    { q: 'The 2004 Indian Ocean tsunami was caused by what?', a: 'a magnitude 9.1 earthquake off the coast of Sumatra', alt: ['huge earthquake near Sumatra'], type: 'recall' },
  ]},
  'wildfire-ecology': { questions: [
    { q: 'What three conditions make up the fire triangle?', a: 'heat, fuel, and oxygen', alt: ['heat fuel oxygen'], type: 'recall' },
    { q: 'How can wildfires benefit ecosystems?', a: 'they clear dead vegetation, recycle nutrients, and promote germination of fire-adapted species', alt: ['clear dead plants recycle nutrients'], type: 'concept' },
    { q: 'What is a prescribed burn?', a: 'a planned fire set under controlled conditions to reduce fuel loads and manage ecosystems', alt: ['controlled fire to reduce fuel'], type: 'recall' },
    { q: 'Climate change increases wildfire risk by doing what?', a: 'raising temperatures, reducing moisture, and extending dry seasons', alt: ['hotter drier conditions longer dry seasons'], type: 'concept' },
    { q: 'What is the wildland-urban interface (WUI)?', a: 'the zone where human development meets or intermingles with wildland vegetation', alt: ['where buildings meet wild areas'], type: 'recall' },
    { q: 'Fire-adapted species like lodgepole pines reproduce after fire how?', a: 'their serotinous cones open only when exposed to the heat of fire', alt: ['cones open with fire heat'], type: 'concept' },
  ]},
};

const SCENARIOS = {
  'standard': [
    { title: 'The Shaking City', focus: 'earthquakes, plate tectonics', text: 'A major city along a convergent plate boundary experiences a magnitude 7.2 earthquake. Buildings collapse, liquefaction occurs in reclaimed land areas, and a small tsunami warning is issued for the nearby coast. Analyze the tectonic setting, explain why different parts of the city experienced different levels of damage, and evaluate the tsunami risk based on the earthquake mechanism.' },
    { title: 'The Vanishing Glacier', focus: 'climate change, hydrology', text: 'A mountain glacier that has supplied freshwater to a valley community for centuries has retreated by 40% in the last 50 years. Downstream river flows are declining in summer, affecting agriculture and drinking water. Explain the connection between climate change and glacier retreat, predict future impacts on water resources, and propose adaptation strategies.' },
    { title: 'Storm of the Century', focus: 'atmospheric science, natural hazards', text: 'A Category 4 hurricane makes landfall on a low-lying coastal city. Storm surge reaches 5 meters, wind speeds exceed 200 km/h, and rainfall totals 500mm in 24 hours. Analyze the atmospheric conditions that intensified this storm, explain the most dangerous aspects of the hurricane, and assess how warming oceans may affect future storms.' },
    { title: 'The Mysterious Rock Layers', focus: 'geology, mineralogy', text: 'A road cut through a hillside reveals layers of limestone with marine fossils, topped by sandstone with plant fossils, then a layer of volcanic ash, and finally a thick layer of glacial till. Reconstruct the environmental history of this location using the principles of superposition and the rock types present.' },
    { title: 'The New Planet', focus: 'astronomy, space exploration', text: 'Astronomers detect an exoplanet orbiting a Sun-like star at 1.1 AU. Transit spectroscopy reveals water vapor, CO2, and trace oxygen in its atmosphere. Its mass is 1.3 Earth masses. Evaluate whether this planet could support life, what additional data would be needed, and design a follow-up observation plan.' },
  ],
  'ap-environmental': [
    { title: 'Cascade of Consequences', focus: 'climate feedbacks, oceanography', text: 'Arctic sea ice has reached a record low. As ice melts, the ice-albedo feedback accelerates warming. Permafrost thawing releases methane. Meanwhile, freshwater influx threatens to slow the thermohaline circulation. Map out all the feedback loops involved, distinguish positive from negative feedbacks, and predict potential tipping points and their global consequences.' },
    { title: 'The Policy Dilemma', focus: 'climate policy, natural hazards', text: 'A developing island nation faces rising sea levels, intensifying cyclones, and coral reef destruction. They must allocate limited funds between coastal defense infrastructure, transitioning to renewable energy, establishing marine protected areas, and developing early warning systems. Analyze the tradeoffs, recommend priorities using climate science data, and address climate justice considerations.' },
    { title: 'The Dead Zone', focus: 'oceanography, atmospheric science, ecology', text: 'A large hypoxic dead zone has formed at a river delta where agricultural runoff meets the ocean. Phytoplankton blooms, then decomposes, depleting oxygen. Ocean acidification compounds the stress. Trace the full chain of causes from land use to ocean chemistry. Propose solutions addressing both the immediate crisis and root causes, and predict how climate change will affect dead zone frequency.' },
  ],
};

// File I/O

function ensureDataDir() { if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true }); }

function profilePath(id) { return path.join(DATA_DIR, String(id).replace(/[^a-zA-Z0-9_-]/g, '_') + '.json'); }

function loadProfile(id) {
  const fp = profilePath(id);
  if (fs.existsSync(fp)) {
    try { return JSON.parse(fs.readFileSync(fp, 'utf8')); }
    catch { fs.renameSync(fp, fp + '.corrupt.' + Date.now()); }
  }
  return { studentId: id, level: null, createdAt: new Date().toISOString(), assessments: [], skills: {} };
}

function saveProfile(p) { ensureDataDir(); fs.writeFileSync(profilePath(p.studentId), JSON.stringify(p, null, 2), 'utf8'); }

// Helpers

function calcMastery(attempts) {
  if (!attempts || !attempts.length) return 0;
  const recent = attempts.slice(-5).filter(a => a.total > 0);
  return recent.length ? Math.round(recent.reduce((s, a) => s + a.score / a.total, 0) / recent.length * 100) / 100 : 0;
}

function masteryLabel(r) { return r >= 0.9 ? 'mastered' : r >= MASTERY_THRESHOLD ? 'proficient' : r >= 0.6 ? 'developing' : r > 0 ? 'emerging' : 'not-started'; }

function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [a[i], a[j]] = [a[j], a[i]]; }
  return a;
}

function pick(arr, n) { return shuffle(arr).slice(0, Math.min(n, arr.length)); }

function norm(s) { return String(s).toLowerCase().trim().replace(/[^a-z0-9 ']/g, ''); }

function resolveSkillKey(level, skill) {
  const ls = SKILLS[level];
  if (!ls) return null;
  for (const [cat, skills] of Object.entries(ls)) {
    if (skills.includes(skill)) return { level, category: cat, skill };
  }
  return null;
}

// Exercise generation

function generateExercise(level, skill, count = 5) {
  const bank = CONTENT_BANKS[skill];
  if (!bank) return { error: `No question bank for ${skill}` };
  const items = pick(bank.questions, count).map(q => ({
    prompt: q.q, answer: q.a, type: q.type,
    alt: q.alt || [],
  }));
  return { type: 'short-answer', skill, level, count: items.length, instruction: 'Answer each question. Short answers are fine.', items };
}

function checkAnswer(type, expected, answer) {
  const ne = norm(expected);
  const na = norm(answer);
  if (ne === na) return true;
  if (ne.includes(na) && na.length > 3) return true;
  if (na.includes(ne) && ne.length > 3) return true;
  return false;
}

function checkWithAlts(expected, alts, answer) {
  if (checkAnswer('short-answer', expected, answer)) return true;
  if (alts && alts.length) {
    for (const alt of alts) {
      if (checkAnswer('short-answer', alt, answer)) return true;
    }
  }
  return false;
}

// Public API

class EarthSpace {
  start(id, level) {
    if (level) this.setLevel(id, level);
    const p = loadProfile(id);
    return { action: 'start', profile: { studentId: p.studentId, level: p.level, createdAt: p.createdAt, totalAssessments: p.assessments.length }, nextSkills: this.next(id) };
  }

  lesson(id) {
    const p = loadProfile(id);
    const level = p.level || 'standard';
    const target = this.next(id, 3).next[0];
    if (!target) return { message: `All skills at ${level} level are proficient! Ready for next level.`, level };
    const exercise = generateExercise(level, target.skill, 5);
    const scenario = SCENARIOS[level] ? pick(SCENARIOS[level], 1)[0] : null;
    return {
      studentId: id, level, targetSkill: target, exercise, scenario,
      lessonPlan: {
        review: 'Review previously learned concepts (2-3 min)',
        teach: `Introduce/reinforce: ${target.category} > ${target.skill}`,
        practice: `Complete ${exercise.count || 0} practice items`,
        apply: scenario ? `Analyze scenario: "${scenario.title}"` : 'Apply concepts to a real-world example',
        extend: `Connect ${target.skill} to related earth & space science concepts`,
      },
    };
  }

  exercise(id, skill) {
    const level = loadProfile(id).level || 'standard';
    if (skill) { return generateExercise(level, skill, 5); }
    const n = this.next(id, 1).next;
    return n.length ? generateExercise(level, n[0].skill, 5) : { message: 'All skills proficient at current level!' };
  }

  check(id, type, expected, answer) {
    let alts = [];
    for (const [, bank] of Object.entries(CONTENT_BANKS)) {
      for (const q of bank.questions) {
        if (norm(q.a) === norm(expected)) { alts = q.alt || []; break; }
      }
      if (alts.length) break;
    }
    const correct = checkWithAlts(expected, alts, answer);
    return { correct, expected, studentAnswer: answer };
  }

  record(id, level, category, skill, score, total, notes) {
    if (!SKILLS[level]) throw new Error(`Unknown level: ${level}. Valid: ${Object.keys(SKILLS).join(', ')}`);
    if (!SKILLS[level][category]) throw new Error(`Unknown category '${category}' for ${level}`);
    if (!SKILLS[level][category].includes(skill)) throw new Error(`Unknown skill '${skill}' in ${level}/${category}`);
    if (typeof total !== 'number' || total <= 0) throw new Error('total must be positive');
    if (typeof score !== 'number' || score < 0 || score > total) throw new Error(`score must be 0-${total}`);

    const p = loadProfile(id);
    if (!p.level) p.level = level;
    const entry = { date: new Date().toISOString(), level, category, skill, score, total, notes: notes || '' };
    p.assessments.push(entry);
    const key = `${level}/${category}/${skill}`;
    if (!p.skills[key]) p.skills[key] = { attempts: [] };
    p.skills[key].attempts.push({ date: entry.date, score, total });
    p.skills[key].mastery = calcMastery(p.skills[key].attempts);
    p.skills[key].label = masteryLabel(p.skills[key].mastery);
    saveProfile(p);
    return { studentId: id, skill: key, score: `${score}/${total}`, mastery: p.skills[key].mastery, label: p.skills[key].label };
  }

  progress(id) {
    const p = loadProfile(id);
    const level = p.level || 'standard';
    const ls = SKILLS[level] || {};
    const results = {};
    let mastered = 0, total = 0;
    for (const [cat, skills] of Object.entries(ls)) {
      results[cat] = {};
      for (const sk of skills) {
        total++;
        const d = p.skills[`${level}/${cat}/${sk}`];
        results[cat][sk] = d ? { mastery: d.mastery, label: d.label } : { mastery: 0, label: 'not-started' };
        if (d && d.mastery >= MASTERY_THRESHOLD) mastered++;
      }
    }
    return { studentId: id, level, mastered, total, overallPct: total > 0 ? Math.round(mastered / total * 100) : 0, skills: results };
  }

  report(id) {
    const p = loadProfile(id);
    return { studentId: id, level: p.level, progress: this.progress(id), recentAssessments: p.assessments.slice(-20).reverse() };
  }

  next(id, count) {
    count = count || 5;
    const p = loadProfile(id);
    const level = p.level || 'standard';
    const candidates = [];
    for (const [cat, skills] of Object.entries(SKILLS[level] || {})) {
      for (const sk of skills) {
        const d = p.skills[`${level}/${cat}/${sk}`];
        const m = d ? d.mastery : 0;
        if (m < MASTERY_THRESHOLD) candidates.push({ level, category: cat, skill: sk, mastery: m, label: d ? d.label : 'not-started' });
      }
    }
    const order = { developing: 0, emerging: 1, 'not-started': 2 };
    candidates.sort((a, b) => (order[a.label] ?? 3) - (order[b.label] ?? 3) || b.mastery - a.mastery);
    return { studentId: id, level, next: candidates.slice(0, count) };
  }

  catalog(level) {
    if (!level) return { levels: Object.keys(SKILLS) };
    const ls = SKILLS[level];
    if (!ls) return { level, error: `Unknown level. Valid: ${Object.keys(SKILLS).join(', ')}` };
    let total = 0;
    const catalog = {};
    for (const [cat, skills] of Object.entries(ls)) { total += skills.length; catalog[cat] = [...skills]; }
    return { level, skills: catalog, totalSkills: total };
  }

  setLevel(id, level) {
    if (!SKILLS[level]) throw new Error(`Unknown level: ${level}. Valid: ${Object.keys(SKILLS).join(', ')}`);
    const p = loadProfile(id); p.level = level; saveProfile(p);
    return { studentId: id, level };
  }

  scenario(level) {
    const texts = SCENARIOS[level];
    if (!texts) return { error: `No scenarios for ${level}. Available: ${Object.keys(SCENARIOS).join(', ')}` };
    return pick(texts, 1)[0];
  }

  students() {
    ensureDataDir();
    const files = fs.readdirSync(DATA_DIR).filter(f => f.endsWith('.json'));
    return { count: files.length, students: files.map(f => f.replace(/\.json$/, '')) };
  }
}

module.exports = EarthSpace;

// CLI: node earth-space.js <command> [args]
if (require.main === module) {
  const args = process.argv.slice(2);
  const cmd = args[0];
  const api = new EarthSpace();
  const out = d => console.log(JSON.stringify(d, null, 2));

  try {
    switch (cmd) {
      case 'start': {
        const [, id, level] = args;
        if (!id) throw new Error('Usage: start <id> [level]');
        out(api.start(id, level));
        break;
      }
      case 'lesson': { const [, id] = args; if (!id) throw new Error('Usage: lesson <id>'); out(api.lesson(id)); break; }
      case 'exercise': {
        const [, id, skill] = args;
        if (!id) throw new Error('Usage: exercise <id> [skill]');
        out(api.exercise(id, skill));
        break;
      }
      case 'check': {
        const [, , type, expected, answer] = args;
        if (!type || expected === undefined || answer === undefined) throw new Error('Usage: check <id> <type> <expected> <answer>');
        let exp = expected; try { exp = JSON.parse(expected); } catch {}
        out(api.check(args[1], type, exp, answer));
        break;
      }
      case 'record': {
        const [, id, level, cat, skill, sc, tot, ...notes] = args;
        if (!id || !level || !cat || !skill || !sc || !tot) throw new Error('Usage: record <id> <level> <cat> <skill> <score> <total> [notes]');
        out(api.record(id, level, cat, skill, Number(sc), Number(tot), notes.join(' ')));
        break;
      }
      case 'progress': { const [, id] = args; if (!id) throw new Error('Usage: progress <id>'); out(api.progress(id)); break; }
      case 'report': { const [, id] = args; if (!id) throw new Error('Usage: report <id>'); out(api.report(id)); break; }
      case 'next': { const [, id, n] = args; if (!id) throw new Error('Usage: next <id> [count]'); out(api.next(id, n ? Number(n) : 5)); break; }
      case 'catalog': { const [, l] = args; out(api.catalog(l)); break; }
      case 'students': { out(api.students()); break; }
      case 'set-level': { const [, id, l] = args; if (!id || !l) throw new Error('Usage: set-level <id> <level>'); out(api.setLevel(id, l)); break; }
      case 'scenario': { const [, l] = args; if (!l) throw new Error('Usage: scenario <level>'); out(api.scenario(l)); break; }
      default: out({ usage: 'node earth-space.js <command> [args]', commands: ['start','lesson','exercise','check','record','progress','report','next','catalog','students','set-level','scenario'], levels: Object.keys(SKILLS) });
    }
  } catch (err) { out({ error: err.message }); process.exit(1); }
}
